"""Adaptive Document Compositor via Typst.

Conforms to Section 20, 21, 22 of AIWF Document Reconstruction Translator:
- Natural Semantic Flow & Readability-first composition (FREE pagination).
- Typographic hierarchy based on DocumentStyleProfile.
- Widow/orphan protection and heading keep-with-next.
- Compiles publication-grade target PDF via local Typst CLI.
- Generates reconstruction-report.json and source-map.json.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from ir.models import DocumentIR, DocumentStyleProfile, SemanticObject, SemanticObjectType
from .renderer_router import RenderedObject, RendererRouter


def _escape_typst(text: str) -> str:
    if not text:
        return ""
    t = str(text).replace("\\", "\\\\")
    for ch in ("#", "$", "@", "[", "]", "*", "_", "<", ">"):
        t = t.replace(ch, f"\\{ch}")
    return t


class DocumentCompositor:
    """Assembles Document IR into Typst source code and compiles it to PDF."""

    def __init__(self, typst_bin: Optional[str] = None):
        self.typst_bin = typst_bin or shutil.which("typst") or "/opt/homebrew/bin/typst"
        self.is_typst_available = Path(self.typst_bin).exists() if self.typst_bin else False

    def compose_and_compile(
        self,
        ir: DocumentIR,
        output_pdf_path: Union[str, Path],
        process_dir: Union[str, Path],
    ) -> Dict[str, Any]:
        """Full pipeline: Compose Typst source -> Compile to PDF -> Output artifacts."""
        proc_dir = Path(process_dir)
        proc_dir.mkdir(parents=True, exist_ok=True)
        out_pdf = Path(output_pdf_path)
        out_pdf.parent.mkdir(parents=True, exist_ok=True)

        router = RendererRouter(output_dir=proc_dir / "rendered-objects")

        # 1. Compose Typst Document
        typst_source, rendered_objs = self.compose_typst(ir, router)

        typ_file = proc_dir / f"{ir.document_id}_reconstructed.typ"
        typ_file.write_text(typst_source, encoding="utf-8")

        # 2. Compile Typst to PDF
        compile_success = False
        error_msg = ""
        if self.is_typst_available:
            try:
                cmd = [self.typst_bin, "compile", "--root", "/", str(typ_file), str(out_pdf)]
                res = subprocess.run(cmd, capture_output=True, text=True, check=True)
                compile_success = True
            except subprocess.CalledProcessError as e:
                error_msg = f"Typst compilation error: {e.stderr}"
        else:
            error_msg = "Typst binary not found on system."

        # 3. Build Reconstruction Report & Source Map (Section 14 & 37)
        recon_report = self._build_reconstruction_report(ir, rendered_objs)
        source_map = self._build_source_map(ir, rendered_objs)

        # Save artifacts
        (proc_dir / "reconstruction-report.json").write_text(
            json.dumps(recon_report, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        (proc_dir / "source-map.json").write_text(
            json.dumps(source_map, ensure_ascii=False, indent=2), encoding="utf-8"
        )

        return {
            "success": compile_success,
            "output_pdf": str(out_pdf) if compile_success else "",
            "typst_file": str(typ_file),
            "total_objects": len(rendered_objs),
            "fallbacks_count": sum(1 for r in rendered_objs if r.fallback_used),
            "reconstruction_report": recon_report,
            "error": error_msg,
        }

    def compose_typst(
        self, ir: DocumentIR, router: RendererRouter
    ) -> Tuple[str, List[RenderedObject]]:
        """Generates publication-grade Typst document source."""
        lines: List[str] = []
        style = ir.style_profile

        # Running header title
        running_title = ir.title or ""
        if len(running_title) > 60:
            running_title = running_title[:57] + "..."

        # Page configuration
        page_args = [
            f'paper: "{style.page_size}"',
            f'flipped: {str(style.orientation == "landscape").lower()}',
            f"margin: (left: {style.margin_left_pt}pt, right: {style.margin_right_pt}pt, top: {style.margin_top_pt}pt, bottom: {style.margin_bottom_pt}pt)",
            f'header: align(right)[#text(size: 8pt, fill: rgb("666666"))[{_escape_typst(running_title)}]]',
            'footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]]',
        ]
        if style.column_count > 1:
            page_args.append(f"columns: {style.column_count}")

        lines.append(f"""// Generated by AIWF Document Reconstruction Translator
#set page(
  {",\n  ".join(page_args)}
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: {style.body_font_size}pt,
  lang: "{ir.target_language}",
)
#set par(
  justify: true,
  leading: {style.line_height_em}em,
  spacing: {style.paragraph_spacing_em}em,
)
""")

        # Process each semantic object in reading order
        rendered_objects: List[RenderedObject] = []
        sorted_objs = ir.get_objects_sorted()

        for obj in sorted_objs:
            # Skip page headers / footers (already rendered at page setup)
            if obj.type in (SemanticObjectType.HEADER, SemanticObjectType.FOOTER, SemanticObjectType.PAGE_NUMBER):
                continue

            r_res = router.render(obj, ir)
            rendered_objects.append(r_res)
            if r_res.typst_code.strip():
                lines.append(r_res.typst_code)

        return "\n".join(lines), rendered_objects

    def _build_reconstruction_report(
        self, ir: DocumentIR, rendered_objs: List[RenderedObject]
    ) -> Dict[str, Any]:
        """Constructs detailed reconstruction-report.json conforming to Section 37."""
        object_reports = []
        strategy_counts: Dict[str, int] = {}
        fallback_count = 0

        for r in rendered_objs:
            strat_val = r.strategy_used.value
            strategy_counts[strat_val] = strategy_counts.get(strat_val, 0) + 1
            if r.fallback_used:
                fallback_count += 1

            object_reports.append({
                "object_id": r.object_id,
                "type": r.object_type.value,
                "strategy": strat_val,
                "confidence": r.confidence,
                "fallback": r.fallback_used,
                "warning": r.warning,
                "asset_path": r.asset_path,
            })

        return {
            "document_id": ir.document_id,
            "total_objects": len(rendered_objs),
            "strategies_breakdown": strategy_counts,
            "fallback_count": fallback_count,
            "overall_reconstruction_rate": round(
                (len(rendered_objs) - fallback_count) / max(1, len(rendered_objs)), 3
            ),
            "objects": object_reports,
        }

    def _build_source_map(
        self, ir: DocumentIR, rendered_objs: List[RenderedObject]
    ) -> Dict[str, Any]:
        """Builds source-map.json linking source PDF geometry to target objects."""
        mappings = []
        for obj in ir.objects:
            mappings.append({
                "object_id": obj.id,
                "type": obj.type.value,
                "source_page": obj.geometry.page_number,
                "source_bbox": obj.geometry.bbox,
                "strategy": obj.reconstruction_strategy.value,
                "confidence": obj.confidence.to_dict(),
            })

        return {
            "document_id": ir.document_id,
            "source_pdf": ir.source_pdf,
            "target_language": ir.target_language,
            "mappings_count": len(mappings),
            "mappings": mappings,
        }
