// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 85.0pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[透析液成分濃度測定装置の認証指針第2版]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]]
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 10.6pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

1

#v(6pt)
#block(breakable: false)[
  #text(size: 14.0pt, weight: "bold")[Hướng dẫn chứng nhận thiết bị đo nồng độ thành phần dịch lọc máu]
]
#v(2pt)
#v(6pt)
#block(breakable: false)[
  #text(size: 14.0pt, weight: "bold")[Phiên bản 2]
]
#v(2pt)
#v(6pt)
#block(breakable: false)[
  #text(size: 14.0pt, weight: "bold")[Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)
Lời nói đầu]
]
#v(2pt)
Từ năm 2009, Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB) đã thành lập Nhóm công tác (WG) nghiên cứu về đo nồng độ thành phần dịch lọc máu, tiến hành trao đổi ý kiến với các nhà sản xuất chế phẩm lọc máu và nhà sản xuất thiết bị đo nhằm chỉ ra các vấn đề tồn tại và đề xuất giải pháp. Kết quả cho thấy, việc đo nồng độ thành phần dịch lọc máu dựa trên các phương pháp phân tích hóa sinh lâm sàng, do đó việc áp dụng nguyên lý chuẩn hóa của phân tích hóa sinh lâm sàng có thể giải quyết được vấn đề. Từ tháng 7 năm 2013, với sự hợp tác của Ủy ban Chuyên trách POCT thuộc Hội Hóa sinh Lâm sàng Nhật Bản (JSCC), công tác chuẩn hóa đo nồng độ thành phần dịch lọc máu đã được triển khai. Vào tháng 4 năm 2016 và tháng 1 năm 2017, Ủy ban Chuyên trách POCT thuộc JSCC đã công bố các báo cáo dự án về chuẩn hóa đo nồng độ thành phần dịch lọc máu – phương pháp xác định giá trị chứng nhận của mẫu chuẩn đối chiếu dùng thường quy cho dịch lọc máu. Nhờ đó, Viện Mẫu chuẩn Hóa sinh Lâm sàng (ReCCS) đã thiết lập Mẫu chuẩn đối chiếu dùng thường quy cho đo dịch lọc máu (JCCRM 300). Sau đó, Hiệp hội chúng tôi đã phối hợp với các nhà sản xuất liên quan, sử dụng JCCRM 300 làm chuẩn hiệu chuẩn để thực hiện hiệu chuẩn các thiết bị đo nồng độ thành phần dịch lọc máu, đồng thời đánh giá độ chính xác sau hiệu chuẩn cũng như khả năng hoán đổi kết quả đo giữa các thiết bị. Kết quả đã kiểm chứng được rằng, việc hiệu chuẩn từng thông số đo tương ứng của hệ thống bằng chất chuẩn này đảm bảo độ tin cậy nhất định của kết quả đo và đảm bảo tính hoán đổi kết quả đo giữa các hệ thống đo lường.

Theo đó, 5 thông số chuẩn hóa bao gồm Na+, K+, Cl－, pH, HCO3

－. Đối với các thiết bị đo các thông số này, gồm thiết bị chuyên dụng đo nồng độ dịch lọc hoặc hệ thống đo có chế độ đo dịch lọc, sẽ tiến hành đánh giá sự phù hợp (chứng nhận) nhằm xác minh các thông số đã được hiệu chuẩn đúng quy cách, từ đó đảm bảo độ tin cậy ổn định.

Hoạt động chứng nhận theo Hướng dẫn này được thực hiện căn cứ theo Khoản (7) Điều 4 Điều lệ của Hiệp hội.

Trong quá trình xây dựng Hướng dẫn chứng nhận thiết bị đo nồng độ thành phần dịch lọc máu, Ủy ban Xây dựng Hướng dẫn Chứng nhận đã được thành lập và triển khai công việc như dưới đây.

Ủy ban Xây dựng Hướng dẫn Chứng nhận Thiết bị Đo Nồng độ Thành phần Dịch lọc máu

Chủ tịch: Kenichi Kokubo (Khoa Sau đại học Y tế, Đại học Kitasato)
Ủy viên: Yasushi Shimizu (Khoa Xét nghiệm Lâm sàng, Phòng khám Motomachi HD)

Atsushi Murakami (Khoa Kỹ thuật Lâm sàng, Bệnh viện Đại học Y Nữ Tokyo)
Toshihiko Yamake (Khoa Kỹ thuật Lâm sàng, Khoa Kỹ thuật, Đại học Công nghệ Kanagawa)
Quan sát viên:

Katsuhiko Kuwa (Nguyên Trưởng bộ phận Chuẩn Đo lường Vật liệu, Viện AIST)
Hideaki Shirai (Khoa Xét nghiệm Trung tâm, Bệnh viện Rosai Yokohama)
Ngày 24 tháng 4 năm 2017

Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Chủ tịch Hội đồng Quản trị: Toshihiko Yamake

2

1. Đặt vấn đề
Các chế phẩm dịch lọc dùng trong điều trị lọc máu được các công ty dược phẩm sản xuất và phân phối dưới dạng "thuốc dùng trong y tế", các cơ sở sản xuất, phương pháp sản xuất và chất lượng sản phẩm được quản lý chặt chẽ theo Luật Đảm bảo chất lượng, hiệu quả và an toàn của dược phẩm, thiết bị y tế và các quy định liên quan. Dưới sự quản lý của cơ sở lọc máu, chế phẩm chỉ trở thành dịch lọc hoàn chỉnh khi được pha loãng và phối trộn ngay trước khi sử dụng tại thực địa, dùng làm dịch tưới hoặc dịch bù cho quả lọc thận nhân tạo.

Dạng bào chế dịch lọc A/B gồm có lỏng/lỏng, lỏng/bột, bột/bột, và nồng độ thành phần dịch lọc sau khi pha được ghi rõ trong tờ hướng dẫn sử dụng dưới dạng giá trị lý thuyết.

Khi pha chế dịch lọc máu, việc quản lý chất lượng như độ chính xác pha trộn và nồng độ thành phần là vô cùng cần thiết. Gần đây, với nhiều phương pháp lọc máu đa dạng như on-line HDF hay IHDF đưa lượng lớn dịch lọc vào cơ thể, thay đổi tần suất hay thời gian lọc máu, cũng như điều chỉnh thành phần và nồng độ dịch lọc phù hợp với triệu chứng lâm sàng (kể cả trong giai đoạn cấp tính), nhiều đánh giá lâm sàng trong các điều kiện khác nhau đang được tiến hành và thảo luận. Nếu không thể xác nhận chính xác nồng độ dịch lọc thì hiệu quả điều trị sẽ khác biệt, gây ảnh hưởng trực tiếp đến tiên lượng của bệnh nhân. Do đó, việc thực tế kiểm soát nồng độ để "xác nhận chất lượng pha chế dịch lọc" là tối quan trọng.

Trước đây từng có tình trạng kết quả đo khác nhau tùy thuộc vào thiết bị đo, nhưng nhờ việc thiết lập chuẩn hiệu chuẩn cho đo dịch lọc máu, việc đo lường chính xác dịch lọc đã trở nên khả thi.

Hướng dẫn chứng nhận này được ban hành nhằm đảm bảo độ tin cậy của phép đo bằng các thiết bị đo nồng độ thành phần dịch lọc được hiệu chuẩn theo Mẫu chuẩn đối chiếu dùng thường quy cho dịch lọc máu (JCCRM 300), phục vụ quản lý dịch lọc máu phù hợp.
2. Phạm vi áp dụng
Hướng dẫn này quy định phương pháp đánh giá độ chính xác của phép đo và quy trình chứng nhận thiết bị đối với các thiết bị đo Na+, K+, Cl－, pH và HCO3

－hoặc hệ thống đo có chế độ đo dịch lọc được hiệu chuẩn bằng mẫu chuẩn đối chiếu dùng thường quy cho chuẩn hóa đo nồng độ thành phần dịch lọc máu.
3. Từ viết tắt
・HD: Hemodialysis, Lọc máu nhân tạo
・HDF: Hemodiafiltration, Lọc máu thẩm tách bù dịch
・IHDF: Intermittent infusion hemodiafiltration, Lọc máu thẩm tách bù dịch ngắt quãng
・FAES: Flame atomic emission spectrometry, Quang phổ phát xạ ngọn lửa
・IC: Ion chromatography, Sắc ký ion
・ISE: Ion-selective electrode, Điện cực chọn lọc ion
・JCCRM: Japanese-Clinical-Chemistry Use Certified Reference Material, Mẫu chuẩn chứng nhận dùng trong hóa sinh lâm sàng Nhật Bản

・SRM: Standard reference material, Mẫu chuẩn chứng nhận do NIST phân phối
・HCO3

－: Ion bicarbonat (Bicarbonate ion)
・K+: Potassium ion, Ion kali
・Na+: Sodium ion, Ion natri
・Cl－: Chloride ion, Ion clorua
・JSTB: Japanese Society for Technology of Blood Purification, Hiệp hội Kỹ thuật Lọc máu Nhật Bản

・JSCC: Japan Society of Clinical Chemistry, Hội Hóa sinh Lâm sàng Nhật Bản
・NIST: National Institute of Standards and Technology, Viện Tiêu chuẩn và Công nghệ Quốc gia Hoa Kỳ
・ReCCS: Reference Material Institute for Clinical Chemistry Standards, Viện Mẫu chuẩn Hóa sinh Lâm sàng Nhật Bản

Viện Chuẩn chất Hóa học Lâm sàng (ReCCS)

3

4. Định nghĩa thuật ngữ
1) Lọc máu nhân tạo (Hemodialysis - HD)
Lọc máu nhân tạo chủ yếu dựa trên nguyên lý khuếch tán và siêu lọc qua màng bán thấm nhằm loại bỏ các chất cặn bã trong máu, điều chỉnh điện giải và thăng bằng kiềm toan, đồng thời đào thải lượng dịch thừa trong cơ thể.
2) Lọc máu thẩm tách bù dịch (Hemodiafiltration - HDF)
Phương pháp điều trị kết hợp lọc máu và siêu lọc, gồm lọc máu bù dịch gián tiếp (off-line HDF) và lọc máu bù dịch trực tuyến (on-line HDF).
3) Lọc máu thẩm tách bù dịch ngắt quãng (IHDF)
Liệu pháp lọc máu thế hệ mới thực hiện siêu lọc và bù dịch ngắt quãng qua màng lọc.
4) Mẫu chuẩn đối chiếu dùng thường quy (Working Reference Material)
Mẫu chuẩn có đặc tính đo lường cao nhất có thể sử dụng tại một địa điểm hoặc tổ chức nhất định, dùng để hiệu chuẩn các phép đo tại đó. Phương pháp đo dùng xác định giá trị chứng nhận của mẫu chuẩn này được giải thích theo tỷ lượng học và được chứng minh bằng thực nghiệm.
5) Phương pháp ISE
Phương pháp sử dụng điện cực chọn lọc ion (ISE) đáp ứng với ion cụ thể trong dung dịch để đo nồng độ ion mục tiêu trong mẫu.
6) Đo điện thế pha loãng (Phương pháp gián tiếp)
Phương pháp pha loãng mẫu (dung dịch hiệu chuẩn, chuẩn nội, huyết thanh...) bằng đệm có lực ion cao rồi đo nồng độ ion mục tiêu bằng ISE.
7) Đo điện thế không pha loãng (Phương pháp trực tiếp)
Phương pháp cho mẫu tiếp xúc trực tiếp với điện cực để đo nồng độ ion mục tiêu.
8) Quy trình đo chuẩn thực hành (Working reference measurement procedure)
Quy trình đo chuẩn thứ cấp trong liên kết chuẩn đo lường, thường gọi là phương pháp tham chiếu (reference method). Với nồng độ Na+ và K+, phương pháp quang phổ phát xạ ngọn lửa (FAES) được áp dụng; với Cl－, phương pháp chuẩn độ điện lượng và sắc ký ion (IC) được áp dụng.
9) Kiểm chứng (Verification)
Xác nhận thông qua kiểm tra rằng các yêu cầu quy định đã được thỏa mãn.
10) Chứng nhận (Certification)
Đánh giá xem thiết bị có phù hợp với các yêu cầu quy định hay không và cấp giấy chứng nhận sự phù hợp.

5. Thông số đo và thiết bị đo
5.1 Thông số đo
Các thông số đo đối tượng trong Hướng dẫn chứng nhận này gồm Na+, K+, Cl－, pH và HCO3

－.
5.2 Thiết bị đo

Thiết bị đo đối tượng trong Hướng dẫn này là thiết bị đo hoặc hệ thống đo có chế độ đo dịch lọc máu đã được hiệu chuẩn bằng JCCRM 300 đối với Na+, K+, Cl－, pH và HCO3

－.
Sự kết hợp giữa thông số đo và thiết bị đo bao gồm cả trường hợp thiết bị đo Na+, K+, Cl－ độc lập với thiết bị đo pH, HCO3

－.
6. Tiêu chuẩn chứng nhận
Yêu cầu đo lường và giá trị tiêu chuẩn chứng nhận về độ chính xác của kết quả đo quy định trong Hướng dẫn này như sau:

#table(
  columns: (auto, auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[N]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[a]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[+]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[pH\*]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[HCO －
3]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Trong khoảng ±2.2]]],
  [#align(left)[#text(size: 8.5pt)[Trong khoảng ±0.15]]],
  [#align(left)[#text(size: 8.5pt)[Trong khoảng ±2.5]]],
  [#align(left)[#text(size: 8.5pt)[Trong khoảng ±0.032]]],
  [#align(left)[#text(size: 8.5pt)[Trong khoảng ±2.2]]],
)
#v(8pt)
4

6.1 Yêu cầu đo lường
Các yêu cầu đo lường quy định như sau:

Mẫu thử đo lường: Mẫu thử nghiệm chứng nhận do Hội đồng Chứng nhận chỉ định
Giá trị mục tiêu của mẫu thử: T
Số lần đo trên thiết bị (n): 5
Giá trị trung bình đo được trên thiết bị: M
Độ lệch chuẩn của các giá trị đo: s
Độ chệch (Bias) của thiết bị (M－T): B
Khoảng tin cậy 95% của giá trị trung bình: ts/√n = 1.24s (df=4, t0.975=2.776,

n=5)
Độ chính xác phép đo của thiết bị (Cm) = (Dấu của B) { (Giá trị tuyệt đối của B) + (ts/√n) }
= (Dấu của B) { (Giá trị tuyệt đối của B) + 1.24s }
6.2 Giá trị tiêu chuẩn chứng nhận
Giá trị tiêu chuẩn chứng nhận quy định tại Bảng 1. Cụ thể, việc đánh giá dựa trên độ lớn của tổng giữa hiệu số (M - T) và khoảng tin cậy 95% của giá trị trung bình.

Giá trị tiêu chuẩn chứng nhận được tính toán dựa trên biên độ hội tụ từ kết quả của 2 đợt thử nghiệm độ hội tụ thực hiện năm 2016 đối với các thiết bị tham gia sau khi hiệu chuẩn bằng JCCRM 300.
7. Quy trình đo chuẩn thực hành
Quy trình đo chuẩn thực hành dùng thiết lập giá trị mục tiêu của mẫu chứng nhận căn cứ theo phương pháp xác định giá trị chứng nhận của mẫu chuẩn đối chiếu thường quy quy định bởi Ủy ban POCT thuộc JSCC và phương pháp khuyến cáo của Ủy ban Khí máu - Điện giải thuộc JSCC (phương pháp FAES và phương pháp chuẩn độ điện lượng).

8. Thiết bị đo tham gia thử nghiệm chứng nhận
Yêu cầu đối với thiết bị đo đăng ký chứng nhận như sau:

8.1 Yêu cầu kỹ thuật
Thiết bị được cấu hình chuyên dụng để đo Na+, K+, Cl－, pH và HCO3

－trong dịch lọc hoặc có chế độ đo dịch lọc máu, và đã được hiệu chuẩn bằng chuẩn hiệu chuẩn quy định.

Tổ hợp thiết bị và thông số đo gồm: máy đo điện giải Na+, K+, Cl－ hoặc Na+, K+; máy đo khí máu pH, HCO3

－; máy đo tích hợp điện giải và khí máu.
Mỗi model thiết bị đăng ký đại diện 01 máy.
8.2 Chuẩn hiệu chuẩn
Đối với thiết bị đo Na+, K+, Cl－, pH và HCO3

－được cấu hình đo dịch lọc, thiết bị phải được hiệu chuẩn bằng JCCRM 300. Phương pháp hiệu chuẩn cụ thể tuân thủ theo quy trình của nhà sản xuất thiết bị.

(Đơn vị nồng độ: mmol/L)

\*Chỉ áp dụng dịch lọc gốc axetat

5

8.3 Kiểm tra bằng độ chụm trung gian
Đối với thiết bị đo thử nghiệm chứng nhận, phải tính toán độ chụm trung gian trong các điều kiện sau bằng cách sử dụng mẫu kiểm tra độ ổn định để kiểm tra và đảm bảo thiết bị có độ ổn định nhất định.

Ghi chú: Độ chụm trung gian là mức độ lặp lại của kết quả đo khi sử dụng mẫu chứng ổn định, trên cùng một thiết bị, cùng điều kiện đo,

Mức độ chụm của các giá trị đo khi cùng một người thực hiện chỉ thay đổi ngày đo
・Số ngày đo: N ≥ 10 ngày
・Chỉ số thống kê: Giá trị trung bình chung, giá trị đo nhỏ nhất, giá trị đo lớn nhất, dải biến thiên, độ lệch chuẩn, hệ số biến thiên
Lưu ý rằng các trị số liên quan đến độ chụm trung gian này phải được ghi vào mẫu đơn đăng ký quy định khi nộp hồ sơ thử nghiệm chứng nhận.

9. Thử nghiệm chứng nhận
9.1 Mẫu thử nghiệm chứng nhận
Mẫu thử nghiệm chứng nhận được điều chế tuân thủ theo quy định về Mẫu chuẩn đối chiếu dùng thường quy cho dịch lọc máu của Ủy ban POCT thuộc JSCC.

Hình thức mẫu thử nghiệm tương thích với mẫu chuẩn đối chiếu dùng thường quy.

#list(marker: [•])[1) Chủng loại
(1) Gốc axetat
(2) Gốc citrat
2) Mức nồng độ
(1) Na+, K+, Cl－: 2 mức nồng độ cho mỗi chất
(2) pH, HCO3]
－: 1 mức nồng độ cho mỗi thông số
3) Dải nồng độ
(1) Điện giải

Na+, K+, Cl－: 2 mức nồng độ lân cận giá trị chứng nhận của JCCRM 300.
(2) Khí máu

pH, HCO3

－: 1 mức nồng độ lân cận giá trị chứng nhận của JCCRM 300.
4) Quy cách
Mẫu thử nghiệm ở dạng lỏng đóng trong lọ xoáy nắp (screw vial).
5) Hướng dẫn sử dụng
Hướng dẫn sử dụng mẫu thử được gửi kèm theo khi phân phối mẫu.

9.2 Thực hiện thử nghiệm
Thử nghiệm chứng nhận do đơn vị đăng ký tự thực hiện dựa trên quy trình gửi kèm mẫu từ cơ quan tổ chức thử nghiệm. Kết quả đo được điền vào biểu mẫu quy định và gửi đính kèm qua e-mail đến địa chỉ được chỉ định.

Khi báo cáo kết quả, phải nộp đồng thời tệp PDF phiếu dữ liệu gốc (hoặc bản sao) xuất trực tiếp từ máy đo (thể hiện số thứ tự, thời gian, ngày tháng đo...) để xác nhận các phép đo được thực hiện liên tục.

Cơ quan tổ chức thử nghiệm chứng nhận là cơ quan thiết lập chất chuẩn tương ứng (ReCCS). Cơ quan này phụ trách các công việc chuyên môn và đặt ban thư ký xử lý các thủ tục hành chính.

9.3 Thiết lập giá trị mục tiêu
Giá trị mục tiêu của mẫu thử nghiệm chứng nhận được thiết lập là giá trị trung bình của 5 lần đo lặp (n=5) bằng quy trình đo chuẩn thực hành.

6

9.4 Hội đồng Chứng nhận
Hội đồng Chứng nhận gồm các ủy viên từ các hội chuyên ngành liên quan và cơ quan tổ chức thử nghiệm.

#list(marker: [•])[1) Cơ cấu thành phần
Hội đồng Chứng nhận gồm các ủy viên được đề cử từ các ủy ban trực thuộc của 3 tổ chức liên quan sau:
・Ủy ban Học thuật JSTB
・Ủy ban Chuyên trách POCT thuộc JSCC
・Viện Mẫu chuẩn Hóa sinh Lâm sàng (ReCCS)
2) Chủ tịch Hội đồng
Chủ tịch Hội đồng do các ủy viên từ Ủy ban Học thuật JSTB bầu ra.
3) Nhiệm kỳ
Nhiệm kỳ ủy viên là 02 năm và có thể được tái bổ nhiệm.
4) Đánh giá phê duyệt
Hội đồng đánh giá đạt/không đạt dựa trên kết quả thử nghiệm và đối chiếu giá trị tiêu chuẩn chứng nhận. Kết quả được công bố trên website của cơ quan tổ chức và báo cáo tới các hội chuyên ngành.
5) Ban Thư ký
Ban Thư ký Hội đồng Chứng nhận do ReCCS đảm nhiệm.]
9.5 Thời hạn hiệu lực của chứng nhận
Chứng nhận có hiệu lực 01 năm kể từ ngày cấp.
9.6 Lệ phí thử nghiệm chứng nhận
Thử nghiệm chứng nhận có thu phí, bao gồm chi phí điều chế mẫu thử, vận chuyển mẫu, thẩm định của Hội đồng và cấp báo cáo kết quả. Phí cấp Giấy chứng nhận đã được bao gồm trong phí thẩm định.

#list(marker: [•])[1) Mức phí
Mức phí cụ thể được quy định tại Phụ lục.
2) Chuyển khoản
Lệ phí được nộp bằng hình thức chuyển khoản vào tài khoản ngân hàng chỉ định. Thông tin tài khoản và hạn nộp được thông báo trong bản hướng dẫn thử nghiệm.
10. Thủ tục tham gia thử nghiệm chứng nhận
10.1 Thời gian tổ chức thử nghiệm
1) Thử nghiệm chứng nhận được tổ chức định kỳ 1–2 lần/năm (đợt 1 vào nửa đầu năm, đợt 2 vào nửa cuối năm).
2) Thông báo tổ chức
Thông báo tổ chức thử nghiệm được đăng tải trên website cơ quan tổ chức trước thời điểm thực hiện 03 tháng, đồng thời gửi e-mail cho các cơ sở đã đăng ký trước. Phiếu đăng ký có thể tải về từ website hoặc nhận qua e-mail.
3) Trang thông tin điện tử của cơ quan tổ chức:
http://www.reccs.or.jp/]
#align(center)[
  #rect(width: 80%, height: 120pt, stroke: 0.5pt + rgb("aaaaaa"), fill: rgb("f9f9f9"))[
    #align(center + horizon)[#text(size: 8.5pt, fill: rgb("666666"))[[Ảnh nguồn gốc: p7_tbl_0]]]
  ]
]
#v(8pt)
#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[k]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ế]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[認]]],
  [#align(center)[#text(size: 8.5pt)[証]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(left)[#text(size: 8.5pt)[Cấp phát
Giấy chứng nhận]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-A/process/assets/asset_p7_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
7

10.2 Đăng ký thử nghiệm chứng nhận
1) Nộp đơn đăng ký
Đơn đăng ký theo mẫu quy định được gửi đính kèm qua e-mail tới Ban Thư ký trước thời hạn quy định.
2) Thông báo gửi mẫu thử
Sau khi đơn được thụ lý, Ban Thư ký gửi thông báo chuyển mẫu và biểu mẫu báo cáo kết quả qua e-mail.
3) Gửi mẫu thử nghiệm
Mẫu thử được gửi trực tiếp tới người nhận ghi trên đơn đăng ký kèm hướng dẫn sử dụng mẫu.

10.3 Báo cáo kết quả thử nghiệm
Kết quả thử nghiệm được điền vào phiếu báo cáo và gửi qua e-mail trước thời hạn quy định.

10.4 Cấp Giấy chứng nhận
Giấy chứng nhận được gửi chính thức qua đường bưu điện.
11. Sơ đồ quy trình chứng nhận
Sơ đồ quy trình chứng nhận được thể hiện tại Hình 1.

Cơ quan thiết lập chất chuẩn
Hội đồng Chứng nhận
Cơ quan tổ chức thử nghiệm
Nhà sản xuất / phân phối

Đánh giá
kết quả

8

Tài liệu tham khảo
1) Ủy ban Chuyên trách POCT, Hội Hóa sinh Lâm sàng Nhật Bản. Chuẩn hóa đo nồng độ thành phần dịch lọc máu — Phương pháp xác định giá trị chứng nhận của mẫu chuẩn đối chiếu dùng thường quy cho dịch lọc máu. Hóa sinh Lâm sàng 2016;45:140-155.
2) Ủy ban Chuyên trách POCT, Hội Hóa sinh Lâm sàng Nhật Bản. Chuẩn hóa đo nồng độ thành phần dịch lọc máu: Phần bổ sung — Phương pháp xác định giá trị chứng nhận nồng độ ion Cl－ của mẫu chuẩn đối chiếu dùng thường quy cho dịch lọc máu. Hóa sinh Lâm sàng 2017;46:60-63.
3) Viện Mẫu chuẩn Hóa sinh Lâm sàng (ReCCS). Giấy chứng nhận Mẫu chuẩn đối chiếu thường quy dùng đo dịch lọc máu JCCRM 300.
4) Katsuhiko Kuwa, Masao Umemoto. Khái quát về mẫu chuẩn nền mẫu thực — Hệ thống xét nghiệm sinh hóa. Hóa sinh Lâm sàng 2009;38:389-400.
5) Ủy ban Khí máu & Điện giải, Hội Hóa sinh Lâm sàng Nhật Bản. Phương pháp khuyến cáo đo nồng độ natri, kali, clorua trong máu bằng phương pháp điện cực chọn lọc ion: Phương pháp hiệu chuẩn độ chính xác bằng huyết thanh chuẩn. Hóa sinh Lâm sàng 1993;22:279-290.
6) Katsuhiko Kuwa, Wataru Tani. Phương pháp quang phổ phát xạ ngọn lửa. Sổ tay kỹ thuật cơ bản về chuẩn hóa xét nghiệm hóa sinh lâm sàng. Tạp chí Tự động hóa Xét nghiệm Lâm sàng Nhật Bản 2009;34(Suppl. 1):59-65.
7) Mitsuo Sekiguchi. Phương pháp chuẩn độ điện lượng. Sổ tay kỹ thuật cơ bản về chuẩn hóa xét nghiệm hóa sinh lâm sàng. Tạp chí Tự động hóa Xét nghiệm Lâm sàng Nhật Bản 2009;34(Suppl. 1):73-77.
8) Junko Yoda, Koji Hayashi, Masao Umemoto. Định lượng ion clorua trong huyết thanh bằng sắc ký ion sử dụng natri bromua làm chuẩn nội. Phân tích Hóa học 1989;43:763-768.

Ngày 13 tháng 3 năm 2017: Ban hành Phiên bản 1
Ngày 24 tháng 4 năm 2017: Ban hành Phiên bản 2 (Thiết bị đo nồng độ thành phần dịch lọc máu, Giá trị tiêu chuẩn chứng nhận)
