// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 85.0pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[21\_R5\_JSTB\_mongolia]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]],
  columns: 2
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 8.8pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p1_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p1_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Tên dự án: Tập huấn kỹ thuật lọc máu ngoài cơ thể và quản lý chất lượng nước tại Mông Cổ
Đơn vị chủ trì: Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)
Quốc gia thụ hưởng: Mông Cổ
Công nghệ y tế chuyển giao: ① Kỹ thuật lọc máu ngoài cơ thể, ③ Hướng dẫn kiểm soát độ tinh khiết dịch lọc máu

Bối cảnh dự án

Mông Cổ có khoảng 1.200 bệnh nhân lọc máu chu kỳ và khoảng 300 máy lọc máu. Khoảng 50% số máy lọc máu là của Nhật Bản (Nipro Corporation), tuy nhiên kỹ thuật bảo trì tại chỗ vẫn chưa được thiết lập đồng bộ. Công tác điều trị lọc máu có sự tham gia của bác sĩ, điều dưỡng, kỹ sư và kỹ thuật viên, nhưng hệ thống đào tạo về quản lý thiết bị và quản lý chất lượng nước còn chưa đầy đủ. Bên cạnh đó, kỹ sư và kỹ thuật viên còn thiếu kiến thức chuyên sâu về bản thân liệu pháp lọc máu. Nhận được đề nghị từ Hội Thận học Mông Cổ, nhằm nắm bắt thực trạng chất lượng nước sử dụng trong lọc máu, từ năm tài chính 2020, Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB) đã thông qua dự án này để hỗ trợ xây dựng hướng dẫn và tiến hành kiểm tra chất lượng nước tại các cơ sở lọc máu trên toàn lãnh thổ Mông Cổ. Hướng dẫn được ban hành đã được Bộ Y tế Mông Cổ chính thức phổ biến đến các cơ sở y tế.

Mục tiêu dự án

Hợp tác cùng Hội Thận học Mông Cổ và Bệnh viện Quốc gia Số 1, Số 2, Số 3 nhằm triển khai các khóa tập huấn nâng cao năng lực chuyên môn, đặc biệt về mặt kỹ thuật trong điều trị lọc máu cho đội ngũ nhân viên y tế (bác sĩ, điều dưỡng, kỹ sư, kỹ thuật viên) trên toàn Mông Cổ. Đồng thời, tổ chức tập huấn kỹ thuật quản lý chất lượng nước tại các cơ sở nhằm giúp từng đơn vị có thể tự chủ quản lý chất lượng nước, kết hợp đánh giá tính hiệu quả thực tế của hướng dẫn đã ban hành.
1

Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB) xin báo cáo về dự án "Tập huấn kỹ thuật lọc máu ngoài cơ thể

và quản lý chất lượng nước tại Mông Cổ" được thực hiện trong khuôn khổ Dự án Thúc đẩy Chuyển giao Quốc tế Công nghệ Y tế Năm Reiwa 5.

Mông Cổ có khoảng 1.200 bệnh nhân lọc máu chu kỳ và khoảng 300 máy lọc máu. Khoảng 50% máy lọc máu là của Nhật Bản (Nipro),

nhưng kỹ thuật bảo trì tại thực địa chưa được thiết lập. Trong điều trị lọc máu có bác sĩ, điều dưỡng, kỹ sư và kỹ thuật viên tham gia,

tuy nhiên hệ thống đào tạo về quản lý thiết bị và chất lượng nước còn thiếu thốn. Đội ngũ kỹ sư, kỹ thuật viên cũng chưa nắm vững

các kiến thức chuyên sâu liên quan trực tiếp đến điều trị lọc máu.

Theo đề nghị từ Hội Thận học và Hội Lọc máu Mông Cổ, nhằm đánh giá thực trạng nguồn nước dùng trong lọc máu,

từ năm 2020, JSTB đã hỗ trợ xây dựng hướng dẫn cũng như kiểm tra chất lượng nước máy lọc máu trên toàn quốc.

Hướng dẫn sau khi hoàn thành đã được Bộ Y tế Mông Cổ ban hành tới các cơ sở y tế.

Lần này, phối hợp với Hội Thận học Mông Cổ cùng Bệnh viện Quốc gia Số 1, Số 2, Số 3, chúng tôi tổ chức tập huấn

cho nhân viên y tế (bác sĩ, điều dưỡng, kỹ sư, kỹ thuật viên) toàn quốc nhằm nâng cao kỹ thuật lọc máu.

Đồng thời, dự án tập huấn kỹ thuật quản lý chất lượng nước giúp từng cơ sở tự chủ kiểm soát,

qua đó đánh giá tính khả thi và hiệu quả thực tế của hướng dẫn đã ban hành.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p2_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p2_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Cơ cấu tổ chức thực hiện

Mục tiêu tập huấn

【Đối tượng】Nhân viên y tế chuyên khoa lọc máu tại Mông Cổ. Hoạt động tập trung tại các cơ sở y tế địa phương do Hội Thận học Mông Cổ lựa chọn (chủ yếu là các bệnh viện tuyến đầu: Bệnh viện Quốc gia Số 1, Số 2, Số 3).
【Nội dung tập huấn】Tổ chức hội thảo liên tịch giữa Hội Thận học Mông Cổ và JSTB, giảng dạy về chỉ định lọc máu, quản lý đường vào mạch máu, quản lý chất lượng nước... Kiểm tra chất lượng nước tại các cơ sở, tập huấn kỹ thuật định lượng nội độc tố và đếm khuẩn lạc vi khuẩn sống. Đào tạo tại Nhật Bản về điều trị lọc máu cho bệnh nhi.
【Mục tiêu cần đạt】Nâng cao kỹ năng chuyên môn kỹ thuật (chỉ định lọc máu, quản lý đường vào mạch máu, kiểm soát chất lượng nước, lọc máu nhi khoa) cho nhân viên y tế Mông Cổ, đồng thời xác nhận tính hiệu quả thực tế của hướng dẫn chất lượng nước.
2

Thuê ngoài đo kiểm...
Đặt hàng vật tư tiêu hao, thiết bị
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Phối hợp (Chia sẻ thông tin)

Công ty CP Nipro

Hội Lọc máu Mông Cổ

Bệnh viện Quốc gia Số 1
Bệnh viện Quốc gia Số 2
Bệnh viện Quốc gia Số 3
Các bệnh viện tư nhân khác

TUC Mongolia Medical

IVCO

Cử chuyên gia

Cho mượn thiết bị

Bộ Y tế

Cơ quan chủ quản
Đề xuất thiết kế bảo hiểm y tế gắn liền

với hướng dẫn và quy định chuyên môn

Yêu cầu tập huấn

Cơ sở lọc máu trong nước

JSTB đã phối hợp cùng Hội Lọc máu Mông Cổ, BV Quốc gia Số 1, Số 2, Số 3 và các bệnh viện tư nhân

để tổ chức hội thảo thực địa và khóa tập huấn tại Nhật Bản. Đồng thời liên kết với TUC Mongolia Medical và IVCO

để khảo sát tính hiệu quả của hướng dẫn chất lượng nước, kiểm tra các cơ sở chưa đạt chuẩn năm ngoái xem đã đạt chuẩn hay chưa,

và so sánh số liệu đo của điều dưỡng/kỹ thuật viên từng cơ sở với chuyên gia giàu kinh nghiệm (kỹ sư/kỹ thuật viên từng được ta đào tạo)

nhằm xác nhận độ tin cậy của các kết quả đo lường tại từng cơ sở.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#table(
  columns: (2fr, auto, auto, auto, 1fr, auto, auto, auto, auto, auto, 1fr, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[N]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ă]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[m]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ ]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[R]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[e]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[i]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[w]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[a]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ ]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[5]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ ]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[(]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[2]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Tập huấn tại
研修
・Tập huấn điều trị lọc máu
nhi khoa
・Bảo trì thiết bị y tế
chuyên sâu]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[準]]],
  [#align(center)[#text(size: 8.5pt)[備期間]]],
  [#align(center)[#text(size: 8.5pt)[Nhật Bản]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(left)[#text(size: 8.5pt)[参加人数：
期間：2024
日本人専]]],
  [#align(left)[#text(size: 8.5pt)[5名
年1月（計
門家：5名]]],
  [#align(center)[#text(size: 8.5pt)[7日間）]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Tập huấn thực địa
Hội thảo liên tịch
・Hands-on đường vào mạch máu (VA)
・Kỹ thuật lọc máu
Hands-on kỹ thuật lọc máu
・Kỹ thuật lọc máu
Hội thảo
など]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[準備]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[期間]]],
  [#align(center)[#text(size: 8.5pt)[Nhật Bản]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[参加人
期間：
日本人
現地専]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[参加人
期間：
日本人
現地専]]],
  [#align(left)[#text(size: 8.5pt)[数：129 người
2023年8月
専門家：1
門家：14]]],
  [#align(left)[#text(size: 8.5pt)[（5日間）
5名
名]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Khảo sát tính
hiệu quả của hướng dẫn]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[Chuẩn bị]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[検]]],
  [#align(center)[#text(size: 8.5pt)[証]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[期間
現地]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[4日間）]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[期間
現地]]],
  [#align(left)[#text(size: 8.5pt)[：2023年
専門家：]]],
  [#align(left)[#text(size: 8.5pt)[11月～202
2名]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[4年2月（3]]],
  [#align(center)[#text(size: 8.5pt)[4日間）]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p3_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p3_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Nội dung hoạt động dự án trong 1 năm

3

Tại Nhật Bản, chúng tôi tổ chức tập huấn cho bác sĩ thận nhi khoa và điều dưỡng Mông Cổ về lọc máu nhi và bảo trì thiết bị y tế.

Đồng thời tổ chức hội thảo liên tịch tại thực địa. Sau 4 năm mới tổ chức trực tiếp, phía đối tác chuẩn bị rất tích cực,

mang lại nội dung phong phú và thành công. Để khảo sát tính hiệu quả của hướng dẫn, hoạt động kiểm tra chất lượng nước

được điều dưỡng/kỹ thuật viên từng cơ sở và chuyên gia đo song song nhằm xác minh độ tin cậy của số liệu đo.

Kỹ sư của nhà phân phối IVCO tại địa phương cũng đồng hành tham gia đợt khảo sát này.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_0.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_1.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_2.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_3.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_4.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_5.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_6.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_img_7.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p4_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

4

Khóa tập huấn tại Nhật Bản

Các bác sĩ thận nhi khoa và điều dưỡng Mông Cổ đã đến thăm 6 cơ sở y tế để quan sát thực tế quy trình điều trị lọc máu tại Nhật Bản.

Học viên chủ yếu học tập và thực hành về kỹ thuật lọc màng bụng (thẩm phân phúc mạc) và lọc máu ngoài cơ thể cho bệnh nhi.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_0.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_1.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_2.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_3.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_4.png", width: 82pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_5.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_6.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_img_7.png", width: 111pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p5_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

5

Khóa tập huấn tại thực địa Mông Cổ

Khóa tập huấn thực địa tại Mông Cổ có tổng cộng 129 nhân viên y tế tham gia gồm bác sĩ, điều dưỡng, kỹ thuật viên, chuyên gia dinh dưỡng, kỹ thuật viên vật lý trị liệu...

Khóa tập huấn tổ chức đào tạo thực hành (hands-on) về kỹ thuật lọc máu, điều dưỡng lọc máu, lọc màng bụng, vận động liệu pháp, dinh dưỡng, phẫu thuật đường vào mạch máu (PTA),

cùng các bài giảng chuyên sâu về đường vào mạch máu, COVID-19, lọc máu ngoài cơ thể, ghép thận, điều dưỡng lọc máu, lọc màng bụng, dinh dưỡng và vận động liệu pháp.

đã được tiến hành thành công.

Tại hội thảo thực hành lần này, chúng tôi mời bệnh nhân thật tham gia để trực tiếp hướng dẫn thao tác, thực hiện phẫu thuật hoặc tổ chức phiên hỏi đáp thảo luận ca bệnh.

Đồng thời, các bác sĩ trẻ địa phương cũng tham gia dịch tiếng Anh sang tiếng Mông Cổ và thuyết trình tại các buổi học.

Chúng tôi kỳ vọng đội ngũ bác sĩ trẻ này trong tương lai sẽ phát triển thành những chuyên gia đầu ngành nòng cốt.

trong chuyên ngành lọc máu tại địa phương.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#table(
  columns: (auto, 2fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[アウトプット指標]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Trước
thực
hiện
(Kế hoạch)]]],
  [#align(left)[#text(size: 8.5pt)[① Học viên tham gia tập huấn tại Nhật Bản
小児腎臓内科 医師2名、看護師2名、エンジニアもしくはテクニシャン2名
Hiểu trên 90% nội dung tập huấn
②モンゴルでのKhóa tập huấn tại thực địa Mông Cổ参加者：
20 bác sĩ, 20 điều dưỡng, 10 kỹ sư, 20 kỹ thuật viên
・Về lọc máu ngoài cơ thể:
Bác sĩ hiểu 100%, điều dưỡng hiểu 75%, kỹ sư hiểu 50%, kỹ thuật viên hiểu 50%
・Về quản lý chất lượng nước:
Bác sĩ hiểu 75%, điều dưỡng hiểu 50%, kỹ sư hiểu 100%, kỹ thuật viên hiểu 100%
③ Khảo sát chất lượng nước
モンゴル全土の透析施設で水質検査を100%実施し、Khảo sát tính実効性を検証]]],
  [#align(left)[#text(size: 8.5pt)[Sau
thực
hiện
(Kết quả)]]],
  [#align(left)[#text(size: 8.5pt)[① Học viên tham gia tập huấn tại Nhật Bản
小児腎臓内科 医師3名、看護師1名
Hiểu trên 90% nội dung tập huấn
②モンゴルでのKhóa tập huấn tại thực địa Mông Cổ参加者
70 bác sĩ, 36 điều dưỡng, 16 kỹ thuật viên, cùng một số chuyên gia dinh dưỡng và vật lý trị liệu. Tổng cộng 129 người
・Khảo sát ý kiến học viên: 25/129 người phản hồi (tỷ lệ: ~20%)
・ハンズオンHội thảoについて
92% người trả lời hiểu trên 90%, 8% hiểu từ 75-90%
・Về bài giảng lý thuyết:
72% người trả lời hiểu trên 90%, 28% hiểu từ 75-90%
③ Khảo sát chất lượng nước
モンゴル全土の透析施設に対して、水質検査をモンゴルの技術者（エンジニア/テクニシャン）が実施する。新たに1名の現地
のエンジニアを含む2名ですべての透析施設を訪問して測定した。訪問して測定できるエンジニア/テクニシャンを増やすことが
できた。また、実際に施設の看護師やテクニシャンに測定をしてもらい、各施設の看護師/テクニシャンの測定した値と熟練者
（以前より我々が指導しているエンジニア/テクニシャン）の測定した値を比較し、今後各施設での測定に移行できるかどうか検
証するためのデータを得るこtrong các giai đoạn trước. 6]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p6_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p6_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Các chỉ số thành quả và kết quả năm nay

Trong khóa tập huấn tại Mông Cổ, hội thảo thực hành có bệnh nhân tham gia trực tiếp để hướng dẫn thao tác lâm sàng,

thực hiện phẫu thuật hoặc tổ chức phiên hỏi đáp thảo luận ca bệnh. Đây là điểm đổi mới lớn so với các năm trước

và nhận được sự đánh giá rất cao từ học viên.

Đồng thời, các bác sĩ trẻ địa phương tham gia với vai trò phiên dịch tiếng Anh - Mông Cổ và trợ giảng.

Chúng tôi kỳ vọng các bác sĩ này sẽ trở thành chuyên gia nòng cốt. Các bác sĩ Mông Cổ cũng đã tham gia thuyết trình

trong bài giảng (lần đầu tiên thực hiện), là bước tiến rất tốt góp phần nâng cao trình độ kỹ thuật lọc máu tại Mông Cổ.

Về khảo sát chất lượng nước, đoàn gồm 2 người (bổ sung thêm 1 kỹ sư địa phương) đã thăm khám toàn bộ cơ sở,

giúp mở rộng đội ngũ kỹ sư/kỹ thuật viên lành nghề tại chỗ. Ngoài ra, việc để điều dưỡng và kỹ thuật viên cơ sở

tự đo rồi đối chiếu với kết quả của chuyên gia giàu kinh nghiệm đã mang lại dữ liệu nền tảng quý giá

để đánh giá tính khả thi của việc chuyển giao công tác đo kiểm định kỳ cho từng đơn vị sau này.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#table(
  columns: (auto, 2fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[アウトカム指標]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Trước
thực
hiện
(Kế hoạch)]]],
  [#align(left)[#text(size: 8.5pt)[① Học viên sau khi học tập tại Nhật Bản ứng dụng kỹ thuật để bắt đầu điều trị cho bệnh nhi lọc màng bụng.
Tăng số ca điều trị lọc máu ngoài cơ thể cho bệnh nhi.
Học viên nắm vững kỹ thuật để quản lý nồng độ dịch lọc. Triển khai 100% xét nghiệm chất lượng nước (bác sĩ, kỹ sư, kỹ thuật viên), tiến tới đo định kỳ nồng độ nội độc tố và số lượng vi khuẩn sống tại từng cơ sở.
② Kiểm tra chất lượng nước tại 43 cơ sở lọc máu toàn Mông Cổ, nắm bắt 100% thực trạng.
昨年度Khảo sát tính水質管理目標が未達成だった施設が水質管理目標を達成できたかどう
かを確認する。各透析施設の看護師やテクニシャンが測定しても信頼性のある値が得られる
かどうか確認する。]]],
  [#align(left)[#text(size: 8.5pt)[Sau
thực
hiện
(Kết quả)]]],
  [#align(left)[#text(size: 8.5pt)[① Học viên ứng dụng kiến thức từ Nhật Bản để xem xét triển khai điều trị cho bệnh nhi lọc màng bụng (ca thứ 2).
Điều dưỡng/kỹ thuật viên tham gia tập huấn đã tự đo chất lượng nước tại cơ sở, nâng cao hiểu biết về quản lý dịch lọc. Thao tác đo được so sánh với chuyên gia giúp chuẩn hóa kỹ thuật và làm rõ các điểm cần cải thiện.
Nhân viên y tế địa phương đã nhận thức rõ sự cần thiết phải nâng cao toàn diện kỹ thuật lọc máu: đường vào mạch máu, vận động liệu pháp, dinh dưỡng...
Các bác sĩ trẻ địa phương đã hỗ trợ dịch thuật và trợ giảng rất tích cực, giúp bồi dưỡng đội ngũ nhân sự nòng cốt có khả năng dẫn dắt sau này.
②水質は以前より良くなっており、Khảo sát tính効果を検証するこtrong các giai đoạn trước.各施設の看護師
やテクニシャンの手技のレベルアップを確認するためのベースラインのデータを得ることがで
きた。 7]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p7_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p7_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Các chỉ số thành quả và kết quả năm nay

Học viên tập huấn tại Nhật Bản ứng dụng kỹ thuật đã học để chuẩn bị triển khai điều trị cho bệnh nhi lọc màng bụng (ca thứ 2).

ました。

Đồng thời, điều dưỡng và kỹ thuật viên tham gia tập huấn đã tự tiến hành kiểm tra chất lượng nước tại đơn vị của mình,

giúp hiểu sâu hơn về quản lý chất lượng dịch lọc. Thao tác đo đối chiếu với chuyên gia giúp chuẩn hóa kỹ năng và chỉ rõ các điểm

cần hoàn thiện hơn nữa.

Về kỹ thuật lọc máu, nhân viên y tế địa phương đã nhận thức đầy đủ tầm quan trọng của việc nâng cao đồng bộ kỹ thuật:

quản lý đường vào mạch máu, vận động liệu pháp và chế độ dinh dưỡng.

Tại hội thảo thực địa lần này, các bác sĩ trẻ địa phương đã hỗ trợ dịch thuật và trợ giảng rất xuất sắc.

Công tác chuẩn bị chu đáo đã giúp đào tạo được đội ngũ nhân sự kế cận có năng lực dẫn dắt tại chỗ.

Về chất lượng nước, số liệu kiểm tra cho thấy chất lượng đã cải thiện rõ rệt, chứng minh hiệu quả thực tế của hướng dẫn.

Đồng thời đã xây dựng được bộ dữ liệu đường cơ sở để đánh giá sự nâng cao tay nghề của điều dưỡng và kỹ thuật viên các cơ sở.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#table(
  columns: (auto, 2fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[インパクト指標]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Trước
thực
hiện
(Kế hoạch)]]],
  [#align(left)[#text(size: 8.5pt)[① Dựa trên kỹ thuật từ khóa tập huấn, các cơ sở y tế địa phương tự thực hiện kiểm tra chất lượng nước định kỳ.
② Các cơ sở y tế định kỳ mua bộ kit xét nghiệm vi khuẩn sống sản xuất tại Nhật Bản theo hướng dẫn.
dịch lọc máuを用いた水質検査を現地医療機関が外注で行う。
③水質管理ガイドラインが作成されたことにより、Khảo sát tính重要性および意義が示され、モンゴル全土の
tại các cơ sở trên toàn Mông Cổ được cải thiện rõ rệt.]]],
  [#align(left)[#text(size: 8.5pt)[Sau
thực
hiện
(Kết quả)]]],
  [#align(left)[#text(size: 8.5pt)[① Đã kiểm tra chất lượng nước tại 49 cơ sở theo hướng dẫn (nắm bắt 100% thực trạng), làm rõ sự cần thiết
な水質検査の必要性が明らかとなり、それが実施可能となるような施策を現地医師と情報共有しながら考
えることが可能になった。特に、保健省やHội Lọc máu Mông Cổが、「定期的に」検査結果を確認して指導する
体制をつくっていくための基礎データとなると考えている。適切な水質管理方法や測定頻度を明記したガイ
ドライン（手引書）の策定につなげていきたい。
② Chuẩn bị các bước để các cơ sở y tế địa phương có thể định kỳ mua bộ kit xét nghiệm vi khuẩn sống của Nhật Bản.
の準備が進んだ。生菌検査キットやエンドトキシンdịch lọc máu及びその試薬をモンゴル国内で販売可能とな
るように、ニプロ社（生菌検査キットのNhà sản xuất / phân phối）や東亜DKK社（エンドトキシンdịch lọc máu及びその試薬
のNhà sản xuất / phân phối）にモンゴルのデータを示した上で、現地で販売可能な商流について検討していただいた。
日本製エンドトキシンdịch lọc máuについては、IVICO社（モンゴル国内医療機器販売メーカ）に導入されること
が決まった。今後、消耗品の商流とその取り扱いなどが決まっていくことで、水質検査を現地医療機関が外
注で行うことができるようになることが期待できる。
③水質管理ガイドラインが作成されたことにより、Khảo sát tính重要性および意義が示され、dịch lọc máuが導
tại các cơ sở lọc máu toàn Mông Cổ. Đồng thời nâng cao hiểu biết về kỹ thuật lọc máu, tạo tiền đề thúc đẩy trang bị các thiết bị y tế an toàn, hiện đại phục vụ xét nghiệm, quản lý và theo dõi điều trị.]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p8_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p8_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Các chỉ số thành quả và kết quả năm nay

8

Nhờ nắm bắt 100% thực trạng qua đợt kiểm tra chất lượng nước tại các cơ sở lọc máu Mông Cổ theo hướng dẫn,

sự cần thiết của việc kiểm tra định kỳ đã được khẳng định rõ và cùng trao đổi với bác sĩ địa phương về biện pháp thực hiện.

Đây là cơ sở dữ liệu quan trọng để Bộ Y tế và Hội Lọc máu Mông Cổ thiết lập hệ thống định kỳ kiểm tra và chỉ đạo chuyên môn,

tiến tới xây dựng cẩm nang hướng dẫn cụ thể phương pháp quản lý và tần suất đo kiểm phù hợp.

ています。

Công tác chuẩn bị để các cơ sở y tế địa phương có thể định kỳ mua bộ kit xét nghiệm vi khuẩn sống của Nhật Bản đã tiến triển tốt.

Nhằm thương mại hóa bộ kit vi khuẩn sống, máy đo nội độc tố và hóa chất tại Mông Cổ, chúng tôi đã chia sẻ dữ liệu thực tế

với Công ty Nipro và Công ty DKK-TOA để nghiên cứu kênh phân phối phù hợp tại thị trường sở tại.

Máy đo nội độc tố của Nhật Bản đã được thống nhất đưa vào lắp đặt tại Công ty IVCO (nhà phân phối thiết bị y tế Mông Cổ).

Kỳ vọng trong thời gian tới khi chuỗi cung ứng vật tư tiêu hao hoàn thiện, các cơ sở y tế có thể thuận tiện thuê ngoài

dịch vụ xét nghiệm kiểm tra chất lượng nước.

Việc ban hành hướng dẫn quản lý chất lượng nước đã khẳng định ý nghĩa thực tiễn, thúc đẩy đưa máy đo vào sử dụng

và cải thiện rõ rệt chất lượng nước lọc máu toàn quốc. Đồng thời nâng cao hiểu biết về kỹ thuật lọc máu,

tạo đà thúc đẩy trang bị các thiết bị y tế an toàn, hiện đại cho công tác xét nghiệm, quản lý và theo dõi điều trị.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p9_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p9_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Tác động dự án trong chuyển giao quốc tế công nghệ và thiết bị y tế
• Học viên tham gia tập huấn ứng dụng kiến thức và kỹ thuật từ Nhật Bản để xem xét điều trị cho bệnh nhi

lọc màng bụng (ca thứ 2).
• Tại hội thảo thực địa, các bác sĩ trẻ địa phương đã hỗ trợ dịch thuật và hướng dẫn thực hành,

giúp đào tạo nguồn nhân lực nòng cốt có khả năng dẫn dắt sau này.
• Chất lượng nước cải thiện rõ rệt, chứng minh hiệu quả của hướng dẫn đã ban hành

trong các giai đoạn trước.

Tác động dự án trong nâng cao sức khỏe cộng đồng
• Tổng số nhân viên y tế được đào tạo trong dự án (lượt người)
- Tổng số học viên tham gia tập huấn (lý thuyết, thực hành...) tại Nhật Bản
- Tổng số học viên tham gia tập huấn (lý thuyết, thực hành...) tại Mông Cổ
- Tổng số học viên tham gia tập huấn (lý thuyết, thực hành...)
- Tổng số chuyên gia/giảng viên địa phương từng được đào tạo nay trở thành giảng viên/chuyên gia

Tác động của dự án đối với quốc gia thụ hưởng trong năm nay

9

5 người
129 người
134 người
4 người

Về tác động chuyển giao quốc tế công nghệ và thiết bị y tế, học viên tham gia khóa học tại Nhật Bản ứng dụng kiến thức, kỹ thuật

đã học để chuẩn bị triển khai điều trị lọc màng bụng cho bệnh nhi (ca thứ 2).

Việc các bác sĩ trẻ địa phương tham gia dịch thuật và trợ giảng tại hội thảo thực địa đã giúp bồi dưỡng

đội ngũ nhân sự nòng cốt có năng lực chuyên môn vững vàng. Khảo sát thực tế cũng khẳng định chất lượng nước

đã cải thiện rõ rệt, chứng minh hiệu quả tích cực của hướng dẫn đã ban hành trước đây.

Tổng số lượt nhân viên y tế được đào tạo trong dự án là 134 người. Một số chuyên gia địa phương từng được đào tạo

nay đã trở thành giảng viên nòng cốt, chứng minh công tác đào tạo nhân lực đạt hiệu quả thực chất.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p10_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p10_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Nhiệm vụ và thách thức trong tương lai

Thành quả đạt được cho đến nay

#list(marker: [•])[• Qua dự án 3 năm (Năm Reiwa 2～4) về tập huấn kỹ thuật lọc máu, khảo sát thực tế và hỗ trợ soạn thảo hướng dẫn, Hướng dẫn kiểm soát độ tinh khiết dịch lọc máu đã được chính thức ban hành.]
#list(marker: [•])[• Tại Mông Cổ, Công ty Nipro đã tăng cường quan hệ hợp tác với đại lý thiết bị y tế địa phương IVCO, bước đầu triển khai thảo luận về việc cung ứng thiết bị và thiết lập hệ thống bảo trì trong tương lai.]
#list(marker: [•])[• Lấy hướng dẫn kiểm soát độ tinh khiết dịch lọc máu làm đòn bẩy, thiết lập chuỗi cung ứng vật tư tiêu hao phục vụ đo đạc định kỳ, đồng thời hỗ trợ vận động đưa vào cơ chế chi trả bảo hiểm y tế.]
#list(marker: [•])[• Nâng cao hiểu biết về kỹ thuật lọc máu ngoài cơ thể, thúc đẩy đưa các thiết bị y tế cần thiết nhằm nâng cao chất lượng và độ an toàn của điều trị.]
#list(marker: [•])[• Hỗ trợ triển khai điều tra thống kê tại các cơ sở lọc máu Mông Cổ tương tự mô hình Nhật Bản, thúc đẩy ứng dụng hệ thống Thu thập Dữ liệu Điện tử (EDC) và hỗ trợ theo dõi sát thực trạng các cơ sở.]
10

Trong các giai đoạn vừa qua, dự án đã khảo sát chất lượng nước tại các cơ sở lọc máu Mông Cổ và dựa trên số liệu thu được

để xây dựng Hướng dẫn kiểm soát độ tinh khiết dịch lọc máu phù hợp thực tiễn. Các hội thảo đã góp phần nâng cao nhận thức

về tầm quan trọng của quản lý chất lượng nước và phổ biến kỹ thuật lọc máu mới.

Để duy trì kiểm tra chất lượng nước thường xuyên, dự án tăng cường hợp tác với doanh nghiệp phân phối thiết bị y tế sở tại,

thảo luận cụ thể về phương án cung ứng thiết bị và cơ chế bảo trì bảo dưỡng.

Thời gian tới, dựa trên hướng dẫn đã ban hành, chúng tôi tiếp tục hỗ trợ hoàn thiện kênh cung ứng vật tư tiêu hao để phục vụ đo định kỳ,

đồng thời vận động tích hợp vào chính sách bảo hiểm y tế. Tiếp tục duy trì các hội thảo chuyên môn nhằm nâng cao hiểu biết

cho nhân viên y tế và thúc đẩy trang bị các thiết bị y tế cần thiết nâng cao chất lượng và an toàn điều trị.

Bên cạnh đó, hỗ trợ triển khai điều tra thống kê cơ sở lọc máu toàn quốc tương tự mô hình Nhật Bản,

đẩy mạnh ứng dụng hệ thống Thu thập Dữ liệu Điện tử (EDC) để theo dõi sát thực trạng các cơ sở lọc máu.

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[B]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[á]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p11_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-B/process/assets/asset_p11_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Hiệp hội Kỹ thuật Lọc máu Nhật Bản (JSTB)

Kế hoạch dự án trong tương lai

• Quản lý chất lượng nước

Khảo sát chất lượng nước toàn bộ cơ sở → Tập huấn & hỗ trợ xây dựng hướng dẫn → Ban hành hướng dẫn chất lượng nước dịch lọc (ĐÃ ĐẠT ĐẾN BƯỚC NÀY) → Hỗ trợ xây dựng cẩm nang cải thiện chất lượng nước, phổ biến kỹ thuật và thiết bị đo cho nhân viên y tế → Thể chế hóa thành chính sách quốc gia (Tiêu chuẩn cơ sở) → Nâng cao tay nghề tại chỗ, tăng số lượng bệnh nhân được điều trị chất lượng cao → Đóng góp nâng cao sức khỏe cộng đồng và chất lượng y tế của quốc gia thụ hưởng.

• Triển khai điều tra thống kê tại Mông Cổ

Khảo sát thực trạng và hỗ trợ nghiên cứu hệ thống điều tra thống kê → Xây dựng cẩm nang hướng dẫn → Triển khai điều tra thống kê bền vững → Chuyển giao kỹ thuật lọc máu sát với thực tế Mông Cổ → Duy trì các khóa tập huấn thường xuyên tại chỗ → Nhân lực có tay nghề giúp tăng số người được điều trị tốt → Đóng góp nâng cao y tế và sức khỏe cộng đồng quốc gia thụ hưởng.

• Chuyển đổi từ kim kim loại sang kim luồn nhựa, sử dụng máy siêu âm hỗ trợ

chọc kim dưới hướng dẫn siêu âm

Tập huấn thực địa sử dụng thiết bị y tế Nhật Bản → Chứng minh hiệu quả tại chỗ (Thử nghiệm lâm sàng do bác sĩ khởi xướng) → Hoàn thiện chuỗi cung ứng logistics (kết nối nhà sản xuất trong nước) → Thiết bị y tế và kỹ thuật liên quan được ứng dụng rộng rãi tại quốc gia sở tại → Đóng góp nâng cao y tế và sức khỏe cộng đồng quốc gia thụ hưởng.

11

Về kế hoạch tương lai trong quản lý chất lượng nước, sau khi đã hoàn thành ban hành hướng dẫn dịch lọc,

dự án sẽ hỗ trợ biên soạn cẩm nang cải thiện chất lượng nước, phổ biến kỹ thuật và chuyển giao thiết bị đo cho kỹ thuật viên,

hướng tới đưa hướng dẫn vào tiêu chuẩn cơ sở y tế nhằm nâng cao chất lượng dịch lọc và tăng số bệnh nhân được thụ hưởng điều trị an toàn.

画しています。

Về triển khai điều tra thống kê, việc nắm bắt số liệu thực tế sẽ giúp cung cấp hỗ trợ kỹ thuật sát với nhu cầu,

góp phần trực tiếp nâng cao chất lượng điều trị lọc máu trên toàn quốc.

Đồng thời, thúc đẩy chuyển đổi từ kim chọc kim loại sang kim luồn nhựa, khuyến khích sử dụng máy siêu âm

hỗ trợ chọc kim nhằm bảo đảm an toàn tối đa trong lọc máu và nâng cao trình độ y tế của Mông Cổ.

ます。
