// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 45.12pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[平成１５年度北里大学学術国際交流計画書（助成金申請書）]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]]
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 11.0pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

#table(
  columns: (2fr, 2fr, 3fr, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[N]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[g]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ư]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ờ]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Kokubo Kenichi]]],
  [#align(left)[#text(size: 8.5pt)[Nhóm Kỹ thuật Y học, Chuyên ngành Kỹ thuật Lâm sàng · Phó Giáo sư]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Đại diện
Đơn vị đối tác]]],
  [#align(left)[#text(size: 8.5pt)[Đại học Y khoa Quốc gia Mông Cổ (Mông Cổ)]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Phân biệt mới/tiếp tục
Thời gian kế hoạch giao lưu]]],
  [#align(left)[#text(size: 8.5pt)[Mới · Tiếp tục（ ）năm thứ
3 năm (Năm tài chính 2025 ～ 2027)]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
)
#v(8pt)
#table(
  columns: (1fr, 3fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[H]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[o]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Hoạt động giao lưu nghiên cứu]]],
  [#align(left)[#text(size: 8.5pt)[① Tiếp nhận nhà nghiên cứu từ tổ chức học thuật nước ngoài ② Cử giảng viên (nhà nghiên cứu) của Nghiên cứu khoa Y học
③ Thực hiện nghiên cứu chung giữa giảng viên (nhà nghiên cứu) Nghiên cứu khoa Y học và nhà nghiên cứu tổ chức học thuật nước ngoài
④ Tổ chức hội thảo, seminar, v.v.
⑤ Trao đổi thông tin nghiên cứu giữa giảng viên (nhà nghiên cứu) Nghiên cứu khoa Y học và nhà nghiên cứu tổ chức học thuật nước ngoài
⑥ Các hoạt động khác đóng góp cho giao lưu nghiên cứu giữa giảng viên (nhà nghiên cứu) Nghiên cứu khoa Y học và nhà nghiên cứu tổ chức học thuật nước ngoài
（ ）
〔Tên đề tài nghiên cứu chung: 〕]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p1_draw_2.png", width: 80%, fit: "contain")
]
#v(8pt)
Báo cáo thực tích Dự án Thúc đẩy Quốc tế hóa Nghiên cứu khoa Y học Năm tài chính 2025

Ⅰ．Phân loại hoạt động giao lưu (đánh dấu ○ vào mục phù hợp)

Ⅱ．Hoạt động giao lưu

Tóm tắt hoạt động giao lưu (khi nộp đơn)

Trong hoạt động giao lưu này, chúng tôi thực hiện nghiên cứu chung với Đại học Y khoa Quốc gia Mông Cổ nhằm nâng cao chất lượng điều trị suy thận mạn tính, đặc biệt là liệu pháp chạy thận nhân tạo.

Mông Cổ là quốc gia thu nhập trung bình thấp với dân số 3,45 triệu người (2023), GDP bình quân đầu người 5.700 đô la (2023),

hiện tại có khoảng 50 cơ sở chạy thận, số bệnh nhân tăng lên khoảng 1.200 người, tuy nhiên tỷ lệ chỉ khoảng 350 người trên 1 triệu dân (Nhật Bản là 2.700 người), và còn nhiều bệnh nhân chưa được tiếp cận điều trị.

Năm 2022, với sự hỗ trợ của JICA, Bệnh viện Mông Cổ-Nhật Bản được thành lập như bệnh viện trực thuộc

Đại học Y khoa Quốc gia Mông Cổ (Mongolian National University of Medical

Sciences) — đại học y khoa quốc lập duy nhất của Mông Cổ, tạo điều kiện thực hiện lâm sàng, giáo dục và nghiên cứu trong cùng một cơ sở.

状況となった。

Trong hoạt động giao lưu này, giảng viên và nghiên cứu sinh của Đại học Y khoa Quốc gia Mông Cổ cùng giảng viên và nghiên cứu sinh của trường chúng tôi sẽ tiến hành hoạt động

giao lưu thông qua nghiên cứu chung. Đầu tiên, giảng viên và nghiên cứu sinh Mông Cổ sẽ lưu trú ngắn hạn khoảng 1 tháng tại Đại học Kitasato để chuẩn bị cho nghiên cứu chung.

Lập kế hoạch cụ thể về nội dung nghiên cứu chung. Chủ yếu liên quan đến nghiên cứu điều trị chạy thận sử dụng mô hình động vật,

cũng như nghiên cứu lâm sàng (nghiên cứu quan sát) được thực hiện tại chỗ. Giữa Nhật Bản và

Mông Cổ, trong bối cảnh khí hậu và chế độ ăn uống khác nhau, chúng tôi sẽ tiến hành nghiên cứu nhằm làm rõ liệu pháp lọc máu chịu ảnh hưởng như thế nào bởi sự khác biệt môi trường đó và điều kiện điều trị tối ưu thay đổi ra sao.

Nghiên cứu sinh của Nghiên cứu khoa Y học cũng sẽ tham gia vào các hoạt động này. Sau đó, phía Nhật Bản sẽ thăm Mông Cổ để thực hiện nghiên cứu chung, đồng thời nghiên cứu sinh

cũng sẽ tiến hành nghiên cứu cần thiết trong nước,

và phát biểu kết quả tại hội nghị quốc tế ở Mông Cổ hoặc các quốc gia khác. Nghiên cứu sinh của hai trường

hợp tác thực hiện nghiên cứu chung với tầm nhìn quốc tế nhằm thúc đẩy

quốc tế hóa hoạt động giáo dục và nghiên cứu của chương trình sau đại học.

#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_0.png", width: 126pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_1.png", width: 123pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_2.png", width: 124pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_3.png", width: 128pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_4.png", width: 123pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_5.png", width: 124pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
Tóm tắt · Thành quả hoạt động giao lưu (thực tế)

Kokubo, Kobayashi, nghiên cứu sinh Zhao và Saito đã thăm Mông Cổ từ ngày 7 đến ngày 13 tháng 8 (sử dụng nguồn ngân sách khác).

Tại thành phố Ulaanbaatar, nhóm đã tham quan Trung tâm Chạy thận Medivic, Khoa Chạy thận Bệnh viện Bà mẹ và Trẻ em Quốc gia, Trung tâm Chạy thận ICU, v.v.

Ngoài ra tham quan Khoa Chạy thận của Trung tâm Chẩn đoán Điều trị Khu vực tại thành phố Dalandzadgad, tỉnh Ömnögovi, và thảo luận về tình hình hiện tại với bác sĩ thận học địa phương.

内科医と現状などについてディスカッションした。

Từ ngày 3 tháng 11 đến ngày 15 tháng 11, tiếp nhận 2 nghiên cứu sinh (nghiên cứu sinh tiến sĩ) từ Mông Cổ. Một người là

Dashnyam Enkhsaikhan (bác sĩ thận học tại Bệnh viện Mông Cổ-Nhật Bản, đang theo học chương trình tiến sĩ tại Đại học Y khoa Quốc gia Mông Cổ),

người còn lại là Enkhtuvshin Enkhtamir (giảng viên Khoa Thận học tại Đại học Y khoa Quốc gia Mông Cổ, đang theo học chương trình tiến sĩ tại cùng trường).

Ban đầu dự kiến lưu trú 1 tháng nhưng do không phù hợp lịch trình nên thời gian lưu trú rút lại còn 2 tuần. Đầu tiên tại trường chúng tôi,

hai nghiên cứu sinh đã thực hành kỹ thuật thí nghiệm chạy thận trên chuột và thực hiện phân tích cùng nghiên cứu sinh của trường.

Ngoài ra, dựa trên thực trạng điều trị chạy thận tại Mông Cổ, nhóm đã thảo luận về các thử nghiệm lâm sàng sẽ thực hiện trong tương lai.

どについてのディスカッションを実施した。

Cơ sở chạy thận tại Mông Cổ

Quang cảnh nghiên cứu chung tại Đại học Kitasato

Triển vọng trong tương lai

Trong năm tài chính này, chúng tôi đã thực hiện các công tác chuẩn bị cho nghiên cứu chung. Về mặt thí nghiệm, đây là giai đoạn chuẩn bị để bắt đầu nghiên cứu chung chính thức,

nhưng các đối tác đã được quan sát trực tiếp quá trình thí nghiệm và hiểu rõ những gì có thể thực hiện tại đây.

Chúng tôi đã có thể tiến tới giai đoạn thảo luận đề tài nghiên cứu cho năm tài chính tiếp theo.

Về thí nghiệm, các đối tác mong muốn trong tương lai có thể thực hiện tại Mông Cổ.

Bên cạnh đó, chúng tôi cũng đã thảo luận về nội dung nghiên cứu so sánh lâm sàng giữa Mông Cổ và Nhật Bản.

Cuộc thảo luận này cũng rất thiết thực và đầy đủ nội dung.

Lần này, sinh viên của Nghiên cứu khoa Y học cũng tham gia cùng trong các buổi họp và thí nghiệm. Ban đầu gặp khó khăn trong giao tiếp,

nhưng dần dần các sinh viên đã tích cực trao đổi hơn, đây là cơ hội tốt. Ngoài ra, trong buổi seminar phòng nghiên cứu, các đối tác Mông Cổ

cũng đã chia sẻ về tình hình chạy thận tại Mông Cổ.

Trong tương lai, chúng tôi dự định xác định đề tài nghiên cứu, triển khai nghiên cứu chung thực tế, đồng thời tiến hành các công việc hoàn tất để ký kết hiệp định học thuật.

業を実施していきたいと考えている。
