// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 45.12pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[平成１５年度北里大学学術国際交流計画書（助成金申請書）]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]]
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 11.0pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

#table(
  columns: (auto, 1fr, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[N]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[g]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ư]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ờ]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Kenichi Kokubo]]],
  [#align(left)[#text(size: 8.5pt)[Nhóm Kỹ thuật Y học, Chuyên ngành Kỹ thuật Lâm sàng ·
准教授]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[相 手 機 関
代 表 者]]],
  [#align(left)[#text(size: 8.5pt)[Đại học Y Quốc gia Mông Cổ (Mông Cổ)]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Phân loại Mới / Tiếp tục
Thời gian kế hoạch giao lưu]]],
  [#align(left)[#text(size: 8.5pt)[新規 ・ 継続（ ）年目
3 năm (Năm học 2025 ～ Năm học 2027)]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
)
#v(8pt)
#table(
  columns: (auto, 2fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[H]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[o]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Hoạt động giao lưu nghiên cứu]]],
  [#align(left)[#text(size: 8.5pt)[①海外学術機関の研究者の受入 ②医療系研究科の教員（研究者）の派遣
③医療系研究科の教員（研究者）と海外学術機関の研究者による共同研究の実施
④シンポジウム・Hội thảo等の開催
⑤医療系研究科の教員（研究者）と海外学術機関の研究者の研究に関する情報交換
⑥その他、医療系研究科の教員（研究者）と海外学術機関の研究者の研究交流に資するもの
（ ）
〔共同研究課題名： 〕]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p1_draw_2.png", width: 80%, fit: "contain")
]
#v(8pt)
Báo cáo thành tích Dự án Thúc đẩy Quốc tế hóa Khoa Sau đại học Y tế Năm học 2025

I. Phân loại hoạt động giao lưu (Đánh dấu ○ vào mục phù hợp)

II. Hoạt động giao lưu

Khái quát hoạt động giao lưu (tại thời điểm đăng ký)

Trong hoạt động giao lưu này, chúng tôi thực hiện nghiên cứu chung với Đại học Y Quốc gia Mông Cổ

nhằm nâng cao hiệu quả điều trị suy thận mạn tính, đặc biệt là lọc máu ngoài cơ thể. Mông Cổ có dân số 3,45 triệu người (2023),

GDP bình quân 5.700 USD (2023), thuộc nhóm thu nhập trung bình thấp; hiện có khoảng 50 cơ sở lọc máu, 1.200 bệnh nhân,

đạt khoảng 350 người/1 triệu dân (Nhật Bản là 2.700 người), nhiều bệnh nhân chưa tiếp cận điều trị. Năm 2022, nhờ JICA,

Bệnh viện Mông Cổ - Nhật Bản trực thuộc Đại học Y Quốc gia Mông Cổ (Mongolian National University of Medical

Sciences) – trường y công lập duy nhất tại Mông Cổ – được thành lập, giúp triển khai lâm sàng, đào tạo và nghiên cứu

đồng bộ tại cùng một cơ sở y tế.

Trong hoạt động giao lưu này, giảng viên, học viên sau đại học của ĐH Y Quốc gia Mông Cổ và trường chúng tôi sẽ giao lưu

thông qua nghiên cứu chung. Trước hết, phía Mông Cổ lưu trú ngắn hạn khoảng 1 tháng tại ĐH Kitasato để chuẩn bị

triển khai nghiên cứu chung và lập kế hoạch cụ thể. Nội dung chủ yếu là điều trị lọc máu trên mô hình động vật,

cũng như nghiên cứu lâm sàng (nghiên cứu quan sát) tại thực địa. Giữa Nhật Bản và Mông Cổ có sự khác biệt về

khí hậu và chế độ ăn, nghiên cứu sẽ làm rõ liệu pháp lọc máu ngoài cơ thể chịu ảnh hưởng ra sao và điều kiện

điều trị tối ưu thay đổi thế nào. Học viên sau đại học Khoa Sau đại học Y tế cũng sẽ tham gia các hoạt động này.

Sau đó, đoàn Nhật Bản sang thăm Mông Cổ để nghiên cứu chung; trong nước, học viên tiếp tục thực hiện nghiên cứu

cần thiết và báo cáo kết quả tại các hội nghị quốc tế ở Mông Cổ hoặc các nước. Việc học viên hai trường hợp tác

triển khai nghiên cứu chung với tầm nhìn quốc tế nhằm thúc đẩy mạnh mẽ quá trình quốc tế hóa trong các hoạt động

đào tạo và nghiên cứu của bậc sau đại học.

#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_0.png", width: 126pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_1.png", width: 123pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_2.png", width: 124pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_3.png", width: 128pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_4.png", width: 123pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_img_5.png", width: 124pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/document-C/process/assets/asset_p2_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
Khái quát hoạt động giao lưu · Thành quả (Thực tế thực hiện)

GS. Kokubo, Kobayashi cùng học viên cao học Triệu (Zhao) và Saito thăm Mông Cổ từ 7/8 đến 13/8 (kinh phí khác).

Tại thủ đô Ulaanbaatar, đoàn khảo sát Trung tâm Lọc máu Medivic, phòng lọc máu BV Phụ sản - Nhi Quốc gia, TT Lọc máu ICU,

và khảo sát phòng lọc máu thuộc Trung tâm Chẩn đoán & Điều trị Khu vực tại TP. Dalanzadgad, tỉnh Ömnögovi,

đồng thời thảo luận với các bác sĩ chuyên khoa Thận địa phương về tình hình thực tế.

Từ ngày 3/11 đến 15/11, chúng tôi tiếp nhận 2 nghiên cứu sinh tiến sĩ từ Mông Cổ. Một người là

BS. Dashnyam Enkhsaikhan (Bác sĩ Thận BV Mông Cổ - Nhật Bản, nghiên cứu sinh ĐH Y Quốc gia Mông Cổ),

và ThS/BS. Enkhtuvshin Enkhtamir (Giảng viên Bộ môn Thận ĐH Y Quốc gia Mông Cổ, nghiên cứu sinh cùng trường);

ban đầu dự kiến 1 tháng nhưng do lịch trình nên rút lại 2 tuần. Trước hết tại trường chúng tôi,

hai bạn được thực hành kỹ thuật thí nghiệm lọc máu trên chuột cống (rat), cùng học viên phân tích

và nắm vững thao tác kỹ thuật. Dựa trên thực tế điều trị tại Mông Cổ, hai bên đã thảo luận về

các thử nghiệm lâm sàng sẽ triển khai trong tương lai.

Cơ sở lọc máu tại Mông Cổ

Hình ảnh nghiên cứu chung tại Đại học Kitasato

Triển vọng trong tương lai

Trong năm học này, chúng tôi đã hoàn tất công tác chuẩn bị triển khai nghiên cứu chung. Về thí nghiệm,

đây là giai đoạn chuẩn bị trước khi chính thức bắt đầu, giúp đối tác quan sát và nắm rõ năng lực thực tế

có thể thực hiện tại đây. Hai bên đã bước vào thảo luận chủ đề nghiên cứu cho năm học tiếp theo.

Về thí nghiệm, đối tác mong muốn tương lai có thể triển khai ngay tại Mông Cổ. Đồng thời về nghiên cứu lâm sàng,

hai bên đã thảo luận các nội dung nghiên cứu so sánh giữa Mông Cổ và Nhật Bản, đạt được nội dung thảo luận

vô cùng phong phú và thực chất.

Lần này, học viên Khoa Sau đại học Y tế cũng tham gia thảo luận và thí nghiệm. Ban đầu còn bỡ ngỡ giao tiếp,

nhưng dần dần đã chủ động trò chuyện, tạo cơ hội học tập rất tốt. Tại seminar nghiên cứu,

các bạn cũng đã giới thiệu về thực trạng lọc máu tại Mông Cổ.

Thời gian tới, chúng tôi sẽ xác định chủ đề, đưa nghiên cứu chung vào vận hành, đồng thời hoàn thiện

các thủ tục chuẩn bị ký kết thỏa thuận hợp tác học thuật.
