document.addEventListener('DOMContentLoaded', () => {
    // DOM Elements
    const workflowsGrid = document.getElementById('workflows-grid');
    const skillsGrid = document.getElementById('skills-grid');
    const modal = document.getElementById('run-modal');
    const closeBtn = document.querySelector('.close-btn');
    const modalTitle = document.getElementById('modal-title');
    const modalDesc = document.getElementById('modal-desc');
    const modalTrigger = document.getElementById('modal-trigger');
    const copyBtn = document.getElementById('copy-btn');

    // Mảng icon ngẫu nhiên để UI trông đẹp mắt nếu không có icon cụ thể
    const faIcons = [
        'fa-briefcase', 'fa-chart-line', 'fa-code', 'fa-bullhorn', 
        'fa-magnifying-glass', 'fa-lightbulb', 'fa-shield-halved', 'fa-laptop-code'
    ];
    let iconIndex = 0;

    function getNextIcon() {
        const icon = faIcons[iconIndex % faIcons.length];
        iconIndex++;
        return icon;
    }

    // Load data from JSON generated by build_dashboard.js
    fetch('data.json')
        .then(response => response.json())
        .then(data => {
            renderItems(data.workflows, workflowsGrid, 'workflow');
            renderItems(data.skills, skillsGrid, 'skill');
        })
        .catch(err => {
            console.error("Lỗi khi tải dữ liệu:", err);
            workflowsGrid.innerHTML = `<p style="color:red">Không tải được dữ liệu. Vui lòng chạy <code>node build_dashboard.js</code> trước.</p>`;
        });

    function renderItems(items, container, type) {
        if (!items || items.length === 0) {
            container.innerHTML = '<p class="text-muted">Chưa có dữ liệu. Hãy thêm file .md vào hệ thống.</p>';
            return;
        }

        container.innerHTML = '';
        items.forEach(item => {
            const icon = getNextIcon();
            const triggerText = item.trigger || (type === 'workflow' ? `/run ${item.name}` : `Dùng lệnh cho: ${item.name}`);
            
            const card = document.createElement('div');
            card.className = 'card';
            card.innerHTML = `
                <div class="card-header">
                    <div class="icon-box"><i class="fa-solid ${icon}"></i></div>
                    <div class="card-title">${item.name}</div>
                </div>
                <div class="card-desc">${item.description || 'Chưa có mô tả chi tiết.'}</div>
                <div class="card-footer">
                    <span class="badge">${type.toUpperCase()}</span>
                    <span><i class="fa-solid fa-arrow-right"></i></span>
                </div>
            `;

            card.addEventListener('click', () => {
                openModal(item.name, item.description, triggerText);
            });

            container.appendChild(card);
        });
    }

    // Modal Logic
    function openModal(name, desc, trigger) {
        modalTitle.textContent = `Thực thi: ${name}`;
        modalDesc.textContent = desc || '';
        modalTrigger.value = trigger;
        
        // Reset copy button state
        copyBtn.innerHTML = '<i class="fa-solid fa-copy"></i>';
        copyBtn.style.background = 'var(--accent)';
        
        modal.classList.add('show');
    }

    function closeModal() {
        modal.classList.remove('show');
    }

    closeBtn.addEventListener('click', closeModal);
    window.addEventListener('click', (e) => {
        if (e.target === modal) {
            closeModal();
        }
    });

    // Copy Logic
    copyBtn.addEventListener('click', () => {
        modalTrigger.select();
        modalTrigger.setSelectionRange(0, 99999); // Mobile
        navigator.clipboard.writeText(modalTrigger.value).then(() => {
            copyBtn.innerHTML = '<i class="fa-solid fa-check"></i>';
            copyBtn.style.background = '#22c55e'; // success green
            
            setTimeout(() => {
                copyBtn.innerHTML = '<i class="fa-solid fa-copy"></i>';
                copyBtn.style.background = 'var(--accent)';
            }, 2000);
        });
    });
});
