// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 85.0pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[日本内科学会雑誌第104巻第7号]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]],
  columns: 2
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 9.2pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p1_img_0.png", width: 42pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p1_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p1_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
はじめに

鉄は代謝・細胞増殖などの生命現象に必須の

元素であるが，その多くは赤血球のヘモグロビ

ンの構成元素として使われ，酸素運搬に機能し

ている．体内で利用される鉄のほとんどは，老

廃化しマクロファージで処理された赤血球由来

の再利用鉄であり，少量の鉄が食事から供給さ

れる．十二指腸，上部空腸から吸収された鉄あ

るいはマクロファージ由来の鉄はトランスフェ

リンによって骨髄へと運搬され，ヘモグロビン

合成に用いられる．鉄の不足はヘモグロビン合

成障害の原因となり，鉄欠乏性貧血の発症に至

る．この鉄欠乏性貧血は日常診療において最も

高い頻度で診る貧血であるが，その主たる原因

は月経，消化管出血などの鉄喪失，成長や妊娠

による需要の増大である．最近，これらの原因

が同定されない鉄欠乏性貧血の発症にHelico-

bacter pyloriが関与しているとの報告がある．本

稿では，生体内鉄代謝の基本的な知識を概説

し，鉄関連貧血，特に鉄欠乏性貧血に関する新

しい知見を紹介する．

1．体内の鉄動態

体内の鉄の総量は3～4 gであり，ヘモグロビ

ン，ミオグロビン，電子伝達系，代謝酵素など

の補欠分子としてのヘム鉄，網内系細胞での貯

蔵鉄として存在する1）．鉄の70％は赤血球に含

まれるヘモグロビン鉄として利用されている

（図1）．赤血球の寿命が120日であることから，

毎日1/120 の赤血球が処理され，新生されてい

る．この処理された赤血球由来の鉄が体外へ排

泄され，新たな赤血球のヘモグロビン合成に必

#v(6pt)
#block(breakable: false)[
  #text(size: 10.3pt, weight: "bold")[鉄代謝と鉄欠乏性貧血 ―最近の知見―]
]
#v(2pt)
要　旨

張替 秀郎 　鉄は酸素運搬に必須の元素である．体内で利用される鉄のほとんどは，

老廃化しマクロファージで処理された赤血球由来の再利用鉄であり，少量

の鉄が食事から供給される．鉄関連貧血で最も頻度が高い貧血は鉄欠乏性

貧血であり，その主たる原因は月経，消化管出血などの鉄喪失，成長や妊

娠による需要の増大である．最近，これらの原因が同定されない鉄欠乏性

貧血の発症にHelicobacter pyloriが関与しているとの知見が得られてい

る．

〔日内会誌　104：1383～1388，2015〕

Key words	 フェリチン，ヘプシジン，Helicobacter pylori

東北大学大学院医学系研究科血液・免疫病学分野 Anemia：From Basic Knowledge to Up-to-Date Treatment. Topics：III. Iron metabolism and iron deficiency anemia―Recent findings―. Hideo Harigae：Department of Hematology and Rheumatology, Tohoku University Graduate School of Medicine, Japan.

Ⅲ. 鉄代謝と鉄欠乏性貧血―最近の知見― トピックス

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[骨]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[髄]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[貯
マクロファージ]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
)
#v(8pt)
#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[貯]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[蔵]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_0.png", width: 65pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_1.png", width: 64pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_2.png", width: 10pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_3.png", width: 20pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_4.png", width: 19pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_5.png", width: 10pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_6.png", width: 10pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_7.png", width: 50pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_8.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_9.png", width: 50pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_10.png", width: 33pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_11.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_12.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_13.png", width: 50pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_14.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_15.png", width: 7pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_16.png", width: 32pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_17.png", width: 8pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_18.png", width: 9pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_19.png", width: 9pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_20.png", width: 13pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_21.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_22.png", width: 29pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_23.png", width: 32pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_24.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_25.png", width: 28pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_26.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_27.png", width: 29pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_28.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_29.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_30.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_31.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_32.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_33.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_34.png", width: 33pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_35.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_36.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_37.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_38.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_39.png", width: 24pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_40.png", width: 24pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_41.png", width: 17pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_42.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_43.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_44.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_45.png", width: 14pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_46.png", width: 34pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_47.png", width: 35pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_48.png", width: 12pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_49.png", width: 13pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_50.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_51.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_52.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_53.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_54.png", width: 9pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_55.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_56.png", width: 11pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_57.png", width: 4pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_58.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_59.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_60.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_61.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_62.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_63.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_64.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_65.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_66.png", width: 8pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_67.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_img_68.png", width: 12pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_draw_0.png", width: 146pt, fit: "contain")
  #v(4pt)
  #text(size: 8.5pt, style: "italic", fill: rgb("333333"))[図1　鉄の体内分布 体内の鉄の総量は3～4 gであり，約70%は赤血 球に含まれるヘモグロビン鉄として利用されて いる．残りは，ミオグロビンや電子伝達系，代謝 酵素などの補欠分子としてのヘム鉄として利用 されている他，網内系細胞での貯蔵鉄として存 在している．]
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_draw_2.png", width: 36pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p2_draw_4.png", width: 155pt, fit: "contain")
]
#v(8pt)
要な鉄が食事から吸収されているかというと，

そうではない．ヒトにおいて鉄の能動的な排出

機構は存在せず，汗や粘膜，上皮細胞の剝離な

どで少量が失われるのみで，喪失量に相応する

少量の鉄が食事から吸収される．このことは，

ほとんどの鉄がin-outで日々入れ替わるわけで

はなく，処理された赤血球由来の鉄は排泄され

ずに再利用されることを意味している．具体的

には，20～25 mgの鉄が新たな赤血球のヘモグ

ロビンとして用いられるが，食事由来の吸収鉄

は1～2 mgであり，それ以外は老廃化して処理

された赤血球由来の鉄である．

この腸管からの吸収鉄，マクロファージから

の再利用鉄は，トランスフェリンと結合し，赤

血球造血の場である骨髄へと運搬される．トラ

ンスフェリン結合鉄はトランスフェリン受容体

と結合し，細胞内に取り込まれた後，pHの低い

エンドソームでトランスフェリンと解離し，金

属トランスポーターであるdivalent metal

transporter 1（DMT1）を介してエンドソーム外

に排出される．エンドソームからミトコンドリ

アに移動した鉄はヘム合成に用いられる．

2．ヘプシジン―フェロポーチンによる鉄利用 調節

血清中のトランスフェリンに結合するために

は腸上皮細胞，マクロファージから細胞外へと

排出される必要があるが，この排出を担うたん

ぱく質がフェロポーチンである．腸上皮細胞，

マクロファージにおいてフェロポーチンの発現

が上昇すれば，トランスフェリンに受け渡され

る鉄が増加，すなわち体内で利用可能な鉄が増

加することになり，逆にその発現が低下すれ

ば，利用可能な鉄が減少することになる．した

がって，これらの細胞におけるフェロポーチン

の発現量は生体における鉄利用にとって極めて

重要であるが，その発現を調節している分子

が，肝臓から分泌されるペプチドであるヘプシ

ジンである．ヘプシジンはフェロポーチンと結

合し，細胞内リソゾームへと誘導することによ

り，フェロポーチンを分解へと導く作用を有す

る2）．すなわち，ヘプシジンの分泌が亢進する

と，フェロポーチンが腸上皮細胞やマクロ

ファージのリソゾームで分解され，その発現が

低下し，結果的にこれらの細胞からの血液中へ

鉄の排出が抑制される．したがって，ヘプシジ

ンは生体における鉄利用の抑制因子であるとい

える．生体内の鉄のバランスは様々な要因によ

り規定されていることから，ヘプシジンの発現

も複数の因子により制御されている（図2）．例

えば，細菌感染や炎症などでは鉄を栄養源とす

る細菌や酸化ストレスからの防御反応としてヘ

プシジンの分泌が亢進し，血液中の鉄レベルが

抑えられる．このヘプシジンの分泌亢進が持続

すると，マクロファージからの鉄排出が抑制さ

れた状態が継続し，結果的に造血に用いる鉄が

不足することになる．この利用可能な鉄が減少

（張替秀郎：日内会誌102：2699-2704，2013）

十二指腸

筋肉 （ミオグロビン） 肝臓

食餌鉄（1 ～2 mg/ 日）

喪失鉄（1 ～2 mg/日）

総量3,000 ～4,000 mg

chọc kim dưới hướng dẫn siêu âm

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[1]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ ]]],
  ),
)
#v(8pt)
#table(
  columns: (auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[2]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[0]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ ]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[～]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_0.png", width: 64pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_1.png", width: 65pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_2.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_3.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_4.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_5.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_6.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_7.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_8.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_9.png", width: 38pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_10.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_11.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_12.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_13.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_14.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_15.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_16.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_17.png", width: 51pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_18.png", width: 41pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_19.png", width: 52pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_20.png", width: 72pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_21.png", width: 73pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_22.png", width: 77pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_23.png", width: 54pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_24.png", width: 78pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_25.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_26.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_27.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_28.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_29.png", width: 53pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_30.png", width: 54pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_31.png", width: 4pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_32.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_33.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_img_34.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_draw_1.png", width: 136pt, fit: "contain")
  #v(4pt)
  #text(size: 8.5pt, style: "italic", fill: rgb("333333"))[図2　鉄の吸収と利用の制御機構 ヘプシジンの分泌が亢進すると，腸上皮細胞やマクロファージにおけるフェロポーチンの発現が低下 し，これらの細胞からの血液中へ鉄の排出が抑制される．したがって，ヘプシジンは生体における鉄利 用の抑制因子であるといえる．ヘプシジンの発現は体内の鉄量，炎症，造血など複数の因子により制御 されている．]
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_draw_2.png", width: 36pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_draw_3.png", width: 54pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p3_draw_4.png", width: 82pt, fit: "contain")
]
#v(8pt)
することで発症する貧血が慢性炎症に伴う貧血

である．

この他，体内の鉄飽和状態，骨髄からの造血

シグナル，低酸素シグナルもヘプシジンの転写

を変化させることが知られている．すなわち，

生体はヘプシジンの発現を多層的に制御するこ

とにより，需要状態に応じた鉄量の調節を行っ

ている．

3．鉄の吸収

鉄のほとんどがリサイクリングで利用されて

いるから，食事からの鉄が重要ではないかとい

うと，決してそのようなことはない．微量なが

らも，毎日鉄が喪失されることを考えると，鉄

のプールを維持するためには一定の鉄の補給が

必要である．さらに，微量であれ，病的な出血

による鉄喪失が加わると，生理的な鉄吸収が少

ないだけに容易に体内の鉄量は負のバランスへ

と傾く．定期的に月経で鉄を失う閉経前の女性

で鉄欠乏性貧血の比率が高率である所以であ

る．食事に含まれる鉄は主として十二指腸，空

腸上部で吸収されるが，食事に含まれる鉄は非

ヘム鉄とヘム鉄の2 種類あり，それぞれ吸収の

メカニズムが異なっている．3 価鉄は胃酸によ

る低いpH状態で可溶化され，腸管上皮の腸管内

腔側細胞膜に存在するduodenal cytochrome b

（Dcytb）によって2 価に還元された後，DMT1

を介して吸収される．ヘム鉄は別のトランス

ポーターであるHCP1（heme carrier protein 1）

によって吸収される．基本的にヘム鉄の吸収率

は10～30％，非ヘム鉄の吸収率は1～8％とさ

れており，ヘム鉄の方が吸収が良好である．ヘ

ム鉄は肉類に多く含まれ，非ヘム鉄は植物系食

品に多く含まれている．表に主たる食品の鉄含

有量を示す（表1） 3）．1日あたりの鉄必要量はお

（張替秀郎：日内会誌102：2699-2704，2013）

マクロファージ

骨髄

赤血球

十二指腸

ヘプシジン

肝臓

炎症シグナル

造血シグナル

鉄飽和シグナル

低酸素シグナル

フェロポーチン

Fe

フェロポーチン

#align(center)[
  #rect(width: 80%, height: 120pt, stroke: 0.5pt + rgb("aaaaaa"), fill: rgb("f9f9f9"))[
    #align(center + horizon)[#text(size: 8.5pt, fill: rgb("666666"))[[Ảnh nguồn gốc: p4_tbl_0]]]
  ]
  #v(4pt)
  #text(size: 8.5pt, style: "italic", fill: rgb("333333"))[表1　鉄分の多い食品の鉄含有量]
]
#v(8pt)
#table(
  columns: (auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[年]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[齢]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[
]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[（]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[男]]],
  [#align(center)[#text(size: 8.5pt)[女]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[0～（月）]]],
  [#align(right)[#text(size: 8.5pt)[6]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(left)[#text(size: 8.5pt)[6～（月）]]],
  [#align(right)[#text(size: 8.5pt)[6]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[15]]],
  [#align(center)[#text(size: 8.5pt)[1～2]]],
  [#align(right)[#text(size: 8.5pt)[7]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[20]]],
  [#align(center)[#text(size: 8.5pt)[3～5]]],
  [#align(right)[#text(size: 8.5pt)[8]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[25]]],
  [#align(center)[#text(size: 8.5pt)[6～8]]],
  [#align(right)[#text(size: 8.5pt)[9]]],
  [#align(right)[#text(size: 8.5pt)[9]]],
  [#align(right)[#text(size: 8.5pt)[30]]],
  [#align(center)[#text(size: 8.5pt)[9～11]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(center)[#text(size: 8.5pt)[10※1]]],
  [#align(right)[#text(size: 8.5pt)[35]]],
  [#align(left)[#text(size: 8.5pt)[12～14]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[35]]],
  [#align(left)[#text(size: 8.5pt)[15～17]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[18～29]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[30～49]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(center)[#text(size: 8.5pt)[12※2]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[50～69]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(center)[#text(size: 8.5pt)[12※2]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(center)[#text(size: 8.5pt)[70以上]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[妊婦
授乳婦]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(left)[#text(size: 8.5pt)[＋8
＋8※3]]],
  [#align(left)[#text(size: 8.5pt)[40
40]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p4_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p4_draw_2.png", width: 155pt, fit: "contain")
]
#v(8pt)
およそ10 mgであるが，成長期の若年者，閉経

前の女性や妊娠中の女性においてはより多くの

鉄摂取が必要である（表2）．

4．鉄欠乏性貧血の疫学と診断

鉄欠乏状態が続くとまず貯蔵鉄が減少し，次

に血清鉄，最終的にヘモグロビン鉄が減少し，

貧血が明らかとなる．すなわち，貧血に至る前

の潜在的鉄欠乏状態を経て，さらに鉄欠乏が進

むと貧血の発症に至ることになる．実際に成長

期の年齢層では，鉄の需要が亢進することから

高率に鉄欠乏状態にあるものの，貧血に至る率

はさほど高くなく，潜在的鉄欠乏状態にとど

まっている．一方で，閉経前の成人女性は，月

経により定期的に鉄を喪失することから，高頻

度で鉄欠乏状態にあり，さらに潜在的鉄欠乏に

とどまらず，10～20％が鉄欠乏性貧血を発症し

ている（表3）．生体内の鉄の貯蔵を最も鋭敏に

反映する指標が血清フェリチン値である．血清

フェリチン値は基本的に組織フェリチン値を反

映しており，鉄欠乏状態では低値を示し，鉄過

剰状態では高値を示す．鉄欠乏性貧血に至る前

の潜在的鉄欠乏では，ヘモグロビン値は正常で

あるが，フェリチン値が低下している．逆に鉄

欠乏性貧血の治療後の経過では，ヘモグロビン

値が正常化した後にフェリチン値が正常化して

くる．したがって，鉄欠乏性貧血の治療におい

ては，ヘモグロビン値の正常化した時点で直ち

に鉄剤の投与を中止せずに，フェリチン値が正

常化した時点で中止するのが望ましい．すなわ

ち，鉄欠乏性貧血の診断と治療において，血清

フェリチン値は主要な検査所見であるといえ

る．実際に，日本鉄バイオサイエンス学会は，

鉄欠乏性貧血の診断基準として，ヘモグロビン

※111歳女子は12 mg/日 ※2閉経後10 mg/日 ※3分娩後6カ月間 （ 健康・栄養情報研究会：日本人の栄養所要量．

第6次改訂）

豚肉（レバー）7.8 mg/60 g いわし（丸干）1.8 mg/2匹 乾燥ひじき 5.5 mg/大匙1杯

牛（レバー） 2.4 mg/60 g ほっき貝 2.2 mg/50 g 切干大根 1.9 mg/20 g

あさり水煮 11.3 mg/30 g 小松菜 2.8 mg/100 g 焼き海苔 0.8 mg/1枚

カツオ 1.5 mg/80 g ホウレンソウ 6.0 mg/束 高野豆腐 0.4 mg/6 g

ホンマグロ 0.9 mg/80 g ゆで大豆 2 mg/100 g ゴマ 1.8 mg/大匙1杯

牛ひれ肉 2 mg/80 g 春菊 1.7 mg/100 g

鶏もも 0.3 m/80 g パセリ 0.8 mg/10 g

たまご 0.9 mg/個 ブロッコリー 0.7 mg/70 g

（日本鉄バイオサイエンス学会：鉄剤の適正使用による貧血治療指針，2009）

#table(
  columns: (auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[平均鉄摂取量]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[潜在的鉄欠乏]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[鉄欠乏性貧血]]],
  ),
  [#align(left)[#text(size: 8.5pt)[小児，青少年]]],
  [#align(left)[#text(size: 8.5pt)[6.9-8.5 mg]]],
  [#align(right)[#text(size: 8.5pt)[68.6%]]],
  [#align(right)[#text(size: 8.5pt)[1.5%]]],
  [#align(center)[#text(size: 8.5pt)[成人男性]]],
  [#align(left)[#text(size: 8.5pt)[7.9-9.8 mg]]],
  [#align(right)[#text(size: 8.5pt)[4.2%]]],
  [#align(right)[#text(size: 8.5pt)[0%]]],
  [#align(left)[#text(size: 8.5pt)[月経のある成人女性]]],
  [#align(left)[#text(size: 8.5pt)[7.0-7.8 mg]]],
  [#align(right)[#text(size: 8.5pt)[36.2%]]],
  [#align(right)[#text(size: 8.5pt)[11.9%]]],
  [#align(left)[#text(size: 8.5pt)[閉経後の成人女性]]],
  [#align(left)[#text(size: 8.5pt)[8.1-9.0 mg]]],
  [#align(right)[#text(size: 8.5pt)[8.5%]]],
  [#align(right)[#text(size: 8.5pt)[2.8%]]],
)
#v(8pt)
#table(
  columns: (auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ヘモグロビン
g/dl]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[血清フェリチン
ng/ml]]],
  ),
  [#align(left)[#text(size: 8.5pt)[鉄欠乏性貧血]]],
  [#align(center)[#text(size: 8.5pt)[＜12]]],
  [#align(center)[#text(size: 8.5pt)[＜12]]],
  [#align(left)[#text(size: 8.5pt)[貧血のない鉄欠乏]]],
  [#align(center)[#text(size: 8.5pt)[≧12]]],
  [#align(center)[#text(size: 8.5pt)[＜12]]],
  [#align(center)[#text(size: 8.5pt)[正常]]],
  [#align(center)[#text(size: 8.5pt)[≧12]]],
  [#align(center)[#text(size: 8.5pt)[≧12]]],
)
#v(8pt)
12 g/dl以下，総鉄結合能360 μg/dl以上，血清

フェリチン値12 ng/ml以下を挙げている（表

4）．臨床的には小球性貧血を呈し，血清鉄が低

下している場合，鉄欠乏性貧血として治療を開

始することが多いと思われるが，慢性炎症に伴

う貧血との鑑別や鉄剤の治療効果の判定に血清

フェリチン値の測定は必須である．

5．鉄欠乏性貧血の治療

日常的に鉄欠乏性貧血症例を診察した場合，

鉄の需要が高まっている成長期もしくは妊娠中

の症例，月経を有する若年女性であれば，鉄剤

の投与を開始し，閉経後や成人男性の場合は積

極的に消化管検査などの検査を実施し，出血源

のスクリーニングを行う．出血源が明らかに

なった場合は原疾患の治療が原則であるが，同

時に鉄剤の投与を行う．通常の治療においては

100～200 mg/日の経口鉄剤が用いられるた

め，鉄の吸収量を考慮すると十分な量の鉄が投

与されることになる．治療開始後，数日で網赤

血球の上昇が認められ，開始時の重症度や出血

のレベルにもよるが，通常2 カ月程度で貧血は

正常化する．したがって，鉄欠乏性貧血に対し

ては原則的に輸血は不要である．

一方で，消化管スクリーニングなどによって

も，鉄喪失の原因が同定されない症例もしばし

ば経験する．Hershkoらは原因がはっきりしな

い，もしくは鉄剤に不応の鉄欠乏性貧血300 例

を解析した結果を報告している．このうち28％

は自己免疫性萎縮性胃炎，5％はセリアック病

であったが，特筆すべきは50％以上にピロリ菌

が陽性であったことである4）．なお，胃切除後

は胃酸分泌が不足するため，鉄の吸収が低下し

鉄欠乏状態になりやすいが，この研究では胃形

成術後の症例は4 例であった．欧米においては

自己免疫性萎縮性胃炎，セリアック病の罹患率

は日本と比べて高いことから，日本において

は，これらの鉄剤不応性鉄欠乏性貧血における

ピロリ菌の関与はより高い可能性がある．この

他，ピロリ菌と鉄剤不応性の鉄欠乏性貧血との

関連を指摘している研究は多く，Yuanらはメタ

アナリシスで，ピロリ菌に感染している症例で

は，鉄剤単剤よりも除菌＋鉄剤治療の方が有意

に貧血の改善が良好であることを報告してい

る5）．最近，本邦からもピロリ菌感染が原因で

と考えられる重症の鉄欠乏性貧血2 例が報告さ

れている6）．症例はいずれも男性でヘモグロビ

ンが4 g/dl台の重症鉄欠乏性貧血で，スクリー

ニングで出血源が同定されず，経口鉄剤のみで

（日本鉄バイオサイエンス学会：鉄剤の適正使用による貧

血治療指針，2009）

2003年国民栄養調査及び日本人の栄養所要量（健康・栄養情報研究会，第6 次改訂）

#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p6_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process/assets/asset_p6_draw_1.png", width: 155pt, fit: "contain")
]
#v(8pt)
は十分な効果が得られなかったが，ピロリ菌除

菌で劇的な貧血の改善が認められている．ピロ

リ菌感染による鉄欠乏性貧血発症のメカニズム

は，胃炎による微小出血，ピロリ菌と生体との

鉄吸収の競合，ピロリ菌感染による萎縮性胃炎

による胃酸分泌不全等提唱されているが，現時

点では断定されていない．しかしながら，多く

の臨床研究の結果から，ピロリ菌感染が確認で

きた鉄剤不応性貧血症例に対しては，ピロリ菌

除菌を試みる必要があると思われる．

おわりに

鉄は酸素運搬をはじめとして生命維持に必須

の元素であるが，ヘプシジンやフェロポーチン

といった，その吸収，利用の調節に関わる分子

が明らかとなったのは最近のことである．これ

らの分子が明らかとなったことで，慢性炎症の

メカニズムが明らかとなり，新たな分子標的薬

の開発につながっている．臨床的にもっとも頻

度が高い貧血は鉄欠乏性貧血であるが，スク

リーニングにより明らかな原因が同定されない

症例も少なくない．これらの症例の発症要因の

1 つとしてピロリ感染による鉄吸収不全が関与

している可能性がいくつかの研究から示唆され

ている．すでに確立されていると思われがちな

鉄代謝のメカニズムや身近で治療が容易と思わ

れがちな鉄欠乏性貧血であるが，未解明な点が

少なからず残されている．今後も古くて新しい

鉄と貧血に関わる新たな知見が得られることを

期待したい．

著者のCOI（conflicts of interest）開示：張替秀郎；講演 料（中外製薬），寄附金（エーザイ，協和発酵キリン）， 寄附講座（中外製薬）

文献

1）	 Andrews NC : Disorders of iron metabolism. N Engl J Med 341 : 1986―1995, 1999. 2）	 Nemeth E, et al : Hepcidin regulates cellular iron efflux by binding to ferroportin and inducing its internalization.  Science 306 : 2090―2093, 2004. 3）	 日本鉄バイオサイエンス学会治療指針作成委員会編：鉄剤の適正使用による貧血治療指針．2009. 4）	 Hershko C, et al : Role of autoimmune gastritis, Hericobacter pylori and celiac disease in refractory or unexpected  iron deficiency anemia. Haematologica 90 : 585―595, 2005. 5）	 Yuan W, et al. Iron deficiency anemia in Hericobacter pylori : meta-analysis of randomized controlled trials. Scand  J Gastroenterol 45 : 665―676, 2010. 6）	 Yamanouchi J, et al : Dramatic and prompt efficacy of Hericobacter pylori eradication in the treatment of severe  refractory iron deficiency anemia in adults. Ann Hematol 93 : 1779―1780, 2014.
