// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 72.0pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[環境技術協力報告書\_BLIND\_TEST]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]]
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 9.5pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

#table(
  columns: (1fr, 3fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[H]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ạ]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Tên dự án]]],
  [#align(left)[#text(size: 8.5pt)[Chuyển giao và phổ biến công nghệ xử lý nước sạch tại khu vực ASEAN]]],
  [#align(center)[#text(size: 8.5pt)[Cơ quan thực hiện]]],
  [#align(left)[#text(size: 8.5pt)[Viện Nghiên cứu Công nghệ Môi trường (ETRI)]]],
  [#align(center)[#text(size: 8.5pt)[Quốc gia đối tượng]]],
  [#align(left)[#text(size: 8.5pt)[Việt Nam, Campuchia, Lào]]],
  [#align(center)[#text(size: 8.5pt)[Thời gian thực hiện]]],
  [#align(left)[#text(size: 8.5pt)[Tháng 4/2024 ～ Tháng 3/2027 (3 năm)]]],
  [#align(center)[#text(size: 8.5pt)[Tổng ngân sách]]],
  [#align(left)[#text(size: 8.5pt)[約1.5億円（150,000千円）]]],
  [#align(center)[#text(size: 8.5pt)[Người phụ trách]]],
  [#align(left)[#text(size: 8.5pt)[Yamada Taro (Nghiên cứu viên chính)]]],
)
#v(8pt)
Environmental Technology Cooperation Project Report — Báo cáo thực tích Quý 2 Năm tài chính 2025

Ⅰ．Tổng quan Dự án

Dự án này là chương trình hợp tác kỹ thuật kéo dài 3 năm nhằm mục đích chuyển giao và phổ biến công nghệ xử lý nước sạch tại khu vực ASEAN (Việt Nam, Campuchia, Lào). Đặc biệt, dự án chú trọng vào việc đảm bảo nguồn nước uống an toàn tại khu vực nông thôn và cải thiện công nghệ xử lý nước thải từ khu công nghiệp.

Các hoạt động chính bao gồm:
① Khảo sát thực địa và phân tích chất lượng nước (đo BOD, COD, SS, pH, v.v.)
② Lắp đặt và hướng dẫn vận hành thiết bị xử lý nước sạch (Mẫu WP-3000A)
③ Thực hiện chương trình đào tạo cho kỹ thuật viên địa phương (tổng cộng 120 người tham gia)
④ Xây dựng hệ thống giám sát chất lượng nước đã xử lý

Trong thực tích Quý 2, đã hoàn thành lắp đặt 2 bộ thiết bị xử lý nước sạch tại khu vực lân cận Hà Nội, Việt Nam, đạt công suất xử lý 500m³/ngày. Tỷ lệ loại bỏ BOD của nước đã xử lý đạt 95,3%, đáp ứng đầy đủ tiêu chuẩn xả nước thải QCVN 14:2008/BTNMT của Việt Nam (BOD≤30mg/L).

#table(
  columns: (2fr, 1fr, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[T]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ê]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[n]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ ]]],
  ),
  [#align(left)[#text(size: 8.5pt)[Đào tạo cơ bản phân tích chất lượng nước]]],
  [#align(left)[#text(size: 8.5pt)[Hà Nội, Việt Nam]]],
  [#align(center)[#text(size: 8.5pt)[35 người]]],
  [#align(center)[#text(size: 8.5pt)[5 ngày]]],
  [#align(left)[#text(size: 8.5pt)[Đào tạo quản lý vận hành thiết bị xử lý nước]]],
  [#align(left)[#text(size: 8.5pt)[Hà Nội, Việt Nam]]],
  [#align(center)[#text(size: 8.5pt)[28 người]]],
  [#align(center)[#text(size: 8.5pt)[3 ngày]]],
  [#align(left)[#text(size: 8.5pt)[Đào tạo công nghệ loại bỏ Asen]]],
  [#align(left)[#text(size: 8.5pt)[Phnom Penh, Campuchia]]],
  [#align(center)[#text(size: 8.5pt)[15 người]]],
  [#align(center)[#text(size: 8.5pt)[4 ngày]]],
  [#align(left)[#text(size: 8.5pt)[Đào tạo kiểm tra chất lượng nước đơn giản]]],
  [#align(left)[#text(size: 8.5pt)[Vientiane, Lào]]],
  [#align(center)[#text(size: 8.5pt)[42 người]]],
  [#align(center)[#text(size: 8.5pt)[2 ngày]]],
)
#v(8pt)
1. Tiến độ cơ sở Việt Nam
Tại tỉnh Vĩnh Phúc, cách Hà Nội khoảng 40km về phía Tây Bắc, đã thực hiện lắp đặt và vận hành thử nghiệm nhà máy thí điểm. Thiết bị này là hệ thống xử lý nước sạch lai ghép (Mẫu: WP-3000A) kết hợp phương pháp keo tụ lắng và phương pháp xử lý sinh học, có các thông số kỹ thuật sau:

・Công suất xử lý: 500m³/ngày
・Tỷ lệ loại bỏ BOD: 95,3%
・Tỷ lệ loại bỏ COD: 89,7%
・Tỷ lệ loại bỏ SS: 98,1%
・Tiêu thụ điện năng: 15,2kWh/m³
・Diện tích lắp đặt: khoảng 200m² (trong tòa nhà hiện có)

2. Tiến độ cơ sở Campuchia
Tại tỉnh Kandal, lân cận Phnom Penh, đã bắt đầu dự án xử lý nước giếng tại khu vực nông thôn. Để đối phó với ô nhiễm Asen tại địa phương (tối đa 0,15mg/L, vượt tiêu chuẩn WHO 0,01mg/L), đã lắp đặt 3 bộ thiết bị loại bỏ Asen bằng phương pháp đồng kết tủa sắt. Nồng độ Asen sau xử lý giảm xuống dưới 0,005mg/L, đạt Hướng dẫn Chất lượng Nước uống của WHO.

3. Tiến độ cơ sở Lào
Tại 2 khu vực trong thành phố Vientiane, đã thực hiện đào tạo vận hành hệ thống xử lý nước đơn giản. 42 kỹ thuật viên địa phương đã tham gia và thực hành các kiến thức cơ bản về phân tích chất lượng nước (đo độ đục, clo dư, số lượng nhóm vi khuẩn đại tràng).

Ⅲ．Thực tích đào tạo

Tóm tắt các chương trình đào tạo đã thực hiện trong quý này như sau.

Kế hoạch cho quý tiếp theo (Quý 3) như sau.

1. Việt Nam: Thực hiện thiết kế và mua sắm thiết bị bổ sung nhằm mở rộng công suất xử lý (từ 500m³/ngày lên 1.000m³/ngày). Đồng thời, xây dựng hệ thống giám sát chung với Sở Tài nguyên và Môi trường địa phương (DoNRE).
2. Campuchia: Hoàn thành lắp đặt thêm 5 bộ thiết bị loại bỏ Asen, mở rộng dân số cung cấp nước uống tại khu vực đối tượng lên khoảng 5.000 người.
3. Lào: Thực hiện Chương trình đào tạo lần thứ 3, hoàn thành bản dịch tiếng địa phương của Sổ tay Vận hành và Bảo trì (O&M) cơ sở xử lý nước.

Ⅴ．Vấn đề và Biện pháp

Hiện nay có 3 vấn đề chính được nêu ra như sau.

(1) Nguồn điện không ổn định: Do mất điện xảy ra thường xuyên ở khu vực nông thôn, đang xem xét lắp đặt pin tích trữ (pin Li-ion, dung lượng 50kWh). Chi phí ước tính khoảng 3,5 triệu Yên/bộ.
(2) Cung cấp phụ tùng tại chỗ: Khó khăn trong việc mua sắm tại chỗ màng lọc (màng MF, kích thước lỗ 0,1μm), cần thiết lập hệ thống cung cấp định kỳ từ Nhật Bản.
(3) Giữ chân nhân lực địa phương: Khoảng 30% học viên đã hoàn thành đào tạo chuyển sang làm việc tại cơ quan khác, việc xây dựng chương trình đào tạo nhân lực liên tục là cấp bách.

Ⅵ．Kết luận

Dự án đã đạt tiến độ theo kế hoạch ban đầu trong Quý 2. Đặc biệt, việc lắp đặt và vận hành thiết bị xử lý nước sạch tại Việt Nam, cũng như triển khai công nghệ loại bỏ Asen tại Campuchia, đã đạt được kết quả vượt mục tiêu. Trong thời gian tới, sẽ tập trung vào việc mở rộng quy mô công suất xử lý và tăng cường hệ thống vận hành tại địa phương.

Hết

Viện Nghiên cứu Công nghệ Môi trường
Nghiên cứu viên chính  Yamada Taro
Ngày 30 tháng 9 năm 2025
