// Generated by AIWF Document Reconstruction Translator
#set page(
  paper: "a4",
  flipped: false,
  margin: (left: 85.0pt, right: 85.0pt, top: 85.0pt, bottom: 85.0pt),
  header: align(right)[#text(size: 8pt, fill: rgb("666666"))[日本内科学会雑誌第104巻第7号]],
  footer: context align(center)[#text(size: 9pt, fill: rgb("666666"))[#counter(page).display("1")]],
  columns: 2
)
#set text(
  font: ("Times New Roman", "Liberation Serif", "Arial"),
  size: 9.2pt,
  lang: "vi",
)
#set par(
  justify: true,
  leading: 0.65em,
  spacing: 0.7em,
)

#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p1_img_0.png", width: 42pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p1_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p1_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
Lời mở đầu

Sắt là nguyên tố thiết yếu cho các hiện tượng

sinh học như chuyển hóa và tăng sinh tế bào, trong đó phần lớn

được sử dụng làm nguyên tố cấu thành hemoglobin của hồng cầu, đảm nhận chức năng vận chuyển oxy.

Hầu hết lượng sắt được sử dụng trong cơ thể là sắt

tái sử dụng có nguồn gốc từ hồng cầu già được xử lý bởi đại thực bào,

và một lượng nhỏ sắt được cung cấp từ thức ăn.

Sắt được hấp thu từ tá tràng và phần trên hỗng tràng,

hoặc sắt có nguồn gốc từ đại thực bào được vận chuyển

bởi transferrin đến tủy xương và được sử dụng

để tổng hợp hemoglobin. Thiếu sắt gây ra rối loạn tổng hợp hemoglobin

dẫn đến phát sinh thiếu máu do thiếu sắt.

Thiếu máu do thiếu sắt là loại thiếu máu có tần suất

cao nhất trong thực hành lâm sàng, và nguyên nhân chính của nó

là mất sắt do kinh nguyệt, xuất huyết tiêu hóa, tăng nhu cầu

do tăng trưởng và thai nghén. Gần đây, có báo cáo cho thấy

Helico-

bacter pylori có liên quan đến sự phát sinh thiếu máu do thiếu sắt không xác định được nguyên nhân. Bài viết này

khái quát kiến thức cơ bản về chuyển hóa sắt trong cơ thể

và giới thiệu những phát hiện mới về thiếu máu liên quan đến sắt, đặc biệt là thiếu máu do thiếu sắt.

しい知見を紹介する．

1. Động thái sắt trong cơ thể

Tổng lượng sắt trong cơ thể là 3～4 g, bao gồm hemoglobin,

myoglobin, chuỗi vận chuyển điện tử, enzyme chuyển hóa,

sắt heme dưới dạng nhóm ngoại của phân tử, và sắt dự trữ trong tế bào lưới nội mô¹⁾.

70% sắt được chứa trong hồng cầu

và được sử dụng dưới dạng sắt hemoglobin

(Hình 1). Do tuổi thọ hồng cầu là 120 ngày,

mỗi ngày có 1/120 lượng hồng cầu được xử lý và tái sinh.

Sắt từ hồng cầu đã xử lý này không bị đào thải ra ngoài cơ thể

mà được tái sử dụng cho tổng hợp hemoglobin của hồng cầu mới.

#v(6pt)
#block(breakable: false)[
  #text(size: 10.3pt, weight: "bold")[Chuyển hóa sắt và thiếu máu do thiếu sắt ―Những phát hiện gần đây―]
]
#v(2pt)
Tóm tắt

Harigae Hideo — Sắt là nguyên tố thiết yếu cho vận chuyển oxy. Hầu hết lượng sắt sử dụng trong cơ thể

là sắt tái sử dụng có nguồn gốc từ hồng cầu già được xử lý bởi đại thực bào, và một lượng nhỏ

sắt được cung cấp từ thức ăn. Thiếu máu có tần suất cao nhất trong các bệnh thiếu máu liên quan đến sắt là thiếu máu do thiếu sắt,

nguyên nhân chính là mất sắt do kinh nguyệt, xuất huyết tiêu hóa, tăng nhu cầu

do tăng trưởng và thai nghén. Gần đây, có bằng chứng cho thấy

Helicobacter pylori liên quan đến sự phát sinh thiếu máu do thiếu sắt không xác định được nguyên nhân.

る．

\[Tạp chí Nội khoa Nhật Bản 104: 1383～1388, 2015\]

Từ khóa	 Ferritin, Hepcidin, Helicobacter pylori

Khoa Huyết học và Bệnh Miễn dịch, Trường Sau đại học Y khoa, Đại học Tohoku. Anemia: From Basic Knowledge to Up-to-Date Treatment. Topics: III. Iron metabolism and iron deficiency anemia―Recent findings―. Hideo Harigae: Department of Hematology and Rheumatology, Tohoku University Graduate School of Medicine, Japan.

Ⅲ. Chuyển hóa sắt và thiếu máu do thiếu sắt ―Những phát hiện gần đây― Chuyên đề

#table(
  columns: (auto, 1fr),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[T]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ủ]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[Dự trữ
Đại thực bào]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
)
#v(8pt)
#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[D]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ự]]],
  ),
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_0.png", width: 65pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_1.png", width: 64pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_2.png", width: 10pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_3.png", width: 20pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_4.png", width: 19pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_5.png", width: 10pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_6.png", width: 10pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_7.png", width: 50pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_8.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_9.png", width: 50pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_10.png", width: 33pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_11.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_12.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_13.png", width: 50pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_14.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_15.png", width: 7pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_16.png", width: 32pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_17.png", width: 8pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_18.png", width: 9pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_19.png", width: 9pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_20.png", width: 13pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_21.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_22.png", width: 29pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_23.png", width: 32pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_24.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_25.png", width: 28pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_26.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_27.png", width: 29pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_28.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_29.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_30.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_31.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_32.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_33.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_34.png", width: 33pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_35.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_36.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_37.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_38.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_39.png", width: 24pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_40.png", width: 24pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_41.png", width: 17pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_42.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_43.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_44.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_45.png", width: 14pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_46.png", width: 34pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_47.png", width: 35pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_48.png", width: 12pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_49.png", width: 13pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_50.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_51.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_52.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_53.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_54.png", width: 9pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_55.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_56.png", width: 11pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_57.png", width: 4pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_58.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_59.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_60.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_61.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_62.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_63.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_64.png", width: 3pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_65.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_66.png", width: 8pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_67.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_img_68.png", width: 12pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_draw_0.png", width: 146pt, fit: "contain")
  #v(4pt)
  #text(size: 8.5pt, style: "italic", fill: rgb("333333"))[Hình 1　Phân bố sắt trong cơ thể. Tổng lượng sắt trong cơ thể là 3～4 g, khoảng 70% được sử dụng dưới dạng sắt hemoglobin chứa trong hồng cầu. Phần còn lại tồn tại dưới dạng myoglobin, chuỗi vận chuyển điện tử, enzyme chuyển hóa]
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_draw_2.png", width: 36pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p2_draw_4.png", width: 155pt, fit: "contain")
]
#v(8pt)
lượng sắt cần thiết có được hấp thu từ thức ăn hay không, thì

không phải vậy. Ở người, không tồn tại cơ chế đào thải sắt chủ động,

chỉ mất một lượng nhỏ qua mồ hôi, niêm mạc, bong tế bào biểu mô,

và chỉ một lượng nhỏ sắt tương ứng với lượng mất đi được hấp thu từ thức ăn.

Điều này có nghĩa là

hầu hết sắt không được trao đổi hàng ngày theo kiểu in-out,

mà sắt từ hồng cầu đã xử lý không bị đào thải

ra ngoài mà được tái sử dụng. Cụ thể,

20～25 mg sắt được sử dụng làm hemoglobin cho hồng cầu mới,

nhưng lượng sắt hấp thu từ thức ăn

chỉ là 1～2 mg, phần còn lại là sắt từ hồng cầu già

đã được xử lý.

Sắt hấp thu từ ống tiêu hóa và sắt tái sử dụng

từ đại thực bào kết hợp với transferrin, và được vận chuyển

đến tủy xương — nơi tạo hồng cầu. Sắt kết hợp

transferrin gắn với thụ thể transferrin,

sau khi được đưa vào trong tế bào, tách khỏi transferrin

trong endosome có pH thấp, và được đào thải

ra ngoài endosome thông qua chất vận chuyển kim loại divalent metal

transporter 1 (DMT1).

Sắt di chuyển từ endosome đến ty thể

được sử dụng để tổng hợp heme.

2. Điều hòa sử dụng sắt bởi hệ thống Hepcidin-Ferroportin

Để kết hợp với transferrin trong huyết thanh,

sắt cần được đào thải từ tế bào biểu mô ruột, đại thực bào ra ngoài tế bào,

và protein đảm nhận việc đào thải này

chính là ferroportin. Nếu biểu hiện ferroportin

tại tế bào biểu mô ruột, đại thực bào tăng lên,

thì lượng sắt được chuyển giao cho transferrin tăng, nghĩa là

lượng sắt có thể sử dụng trong cơ thể tăng lên,

ngược lại nếu biểu hiện giảm,

thì lượng sắt khả dụng sẽ giảm. Do đó,

mức độ biểu hiện ferroportin tại các tế bào này

cực kỳ quan trọng đối với việc sử dụng sắt trong cơ thể,

và phân tử điều hòa biểu hiện đó

chính là hepcidin — một peptide được tiết ra từ gan.

Hepcidin kết hợp với ferroportin,

dẫn ferroportin vào lysosome trong tế bào

để phân giải²⁾. Nghĩa là, khi tiết hepcidin tăng,

ferroportin bị phân giải trong lysosome

của tế bào biểu mô ruột và đại thực bào,

biểu hiện giảm,

kết quả là đào thải sắt từ các tế bào này vào máu

bị ức chế. Do đó, hepcidin

có thể nói là yếu tố ức chế sử dụng sắt trong cơ thể.

Cân bằng sắt trong cơ thể được quy định bởi nhiều yếu tố,

nên biểu hiện hepcidin cũng được điều khiển bởi nhiều nhân tố (Hình 2). Ví dụ,

khi nồng độ sắt huyết thanh tăng hoặc dự trữ sắt trong cơ thể tăng,

biểu hiện hepcidin tăng, qua đó ức chế hấp thu sắt

từ ống tiêu hóa và đào thải sắt từ đại thực bào.

Ngược lại, khi thiếu sắt, biểu hiện hepcidin giảm,

tăng cường hấp thu sắt từ ống tiêu hóa và đào thải

sắt từ đại thực bào. Ngoài ra, viêm nhiễm,

đặc biệt là Interleukin-6 (IL-6) cũng

kích thích biểu hiện hepcidin.

và dự trữ sắt tại gan, tủy xương, đại thực bào.

Tá tràng

cần cân nhắc các nguyên nhân hiếm gặp.

Thiếu máu do thiếu sắt mức độ nhẹ có thể

Mệt mỏi, khó thở khi gắng sức, da niêm mạc nhợt

viêm miệng góc, nuốt khó.

Sử dụng

#table(
  columns: (auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[1]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[～]]],
  ),
)
#v(8pt)
#table(
  columns: (auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[2]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[0]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[～]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[5 mg/日]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_0.png", width: 64pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_1.png", width: 65pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_2.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_3.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_4.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_5.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_6.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_7.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_8.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_9.png", width: 38pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_10.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_11.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_12.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_13.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_14.png", width: 16pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_15.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_16.png", width: 15pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_17.png", width: 51pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_18.png", width: 41pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_19.png", width: 52pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_20.png", width: 72pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_21.png", width: 73pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_22.png", width: 77pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_23.png", width: 54pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_24.png", width: 78pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_25.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_26.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_27.png", width: 5pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_28.png", width: 6pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_29.png", width: 53pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_30.png", width: 54pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_31.png", width: 4pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_32.png", width: 2pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_33.png", width: 0pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_img_34.png", width: 1pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_draw_1.png", width: 136pt, fit: "contain")
  #v(4pt)
  #text(size: 8.5pt, style: "italic", fill: rgb("333333"))[Hình 2　Cơ chế điều hòa hấp thu và sử dụng sắt. Khi tiết hepcidin tăng, biểu hiện ferroportin tại tế bào biểu mô ruột và đại thực bào giảm, ức chế đào thải sắt từ các tế bào này vào máu.]
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_draw_2.png", width: 36pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_draw_3.png", width: 54pt, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p3_draw_4.png", width: 82pt, fit: "contain")
]
#v(8pt)
Hình 2　Cơ chế điều hòa hấp thu và sử dụng sắt.

.

Khi tiết hepcidin tăng, biểu hiện ferroportin tại tế bào biểu mô ruột và đại thực bào giảm,

ức chế đào thải sắt từ các tế bào này vào máu. Ngược lại, khi tiết hepcidin giảm,

biểu hiện ferroportin tăng, tăng cường cung cấp sắt.

Biểu hiện hepcidin được điều hòa bởi

nồng độ sắt, viêm nhiễm, tạo hồng cầu, thiếu oxy.

.

5. Điều trị thiếu máu do thiếu sắt

Điều trị thiếu máu do thiếu sắt bao gồm

bổ sung sắt đường uống và điều trị nguyên nhân cơ bản.

Sắt sulfate, sắt fumarate, sắt gluconate

là các chế phẩm sắt đường uống thường dùng.

Liều khuyến cáo là 100～200 mg sắt nguyên tố/ngày.

Tác dụng phụ đường tiêu hóa (buồn nôn, táo bón, đau bụng)

là vấn đề phổ biến nhất.

Để giảm tác dụng phụ, có thể bắt đầu

với liều thấp và tăng dần.

Sắt truyền tĩnh mạch được chỉ định khi

không dung nạp sắt đường uống,

hoặc khi cần bổ sung sắt nhanh.

Hemoglobin thường bắt đầu tăng

sau 2～4 tuần điều trị sắt đường uống.

Điều trị nên tiếp tục ít nhất 3～6 tháng

sau khi hemoglobin bình thường hóa

để bổ sung đầy đủ dự trữ sắt.

Ferritin huyết thanh là chỉ số theo dõi

hiệu quả điều trị và dự trữ sắt.

Nếu không đáp ứng sau 4～6 tuần điều trị sắt,

cần xem xét lại: tuân thủ điều trị,

nguyên nhân mất sắt tiếp diễn,

hoặc chẩn đoán sai.

Truyền máu chỉ được chỉ định khi

thiếu máu nặng đe dọa tính mạng.

Ngược lại, khi tiết hepcidin giảm, biểu hiện ferroportin tăng,

Kết luận: Hiểu biết về chuyển hóa sắt và vai trò của hepcidin

Tủy xương

Hồng cầu

Tá tràng

Hepcidin

Gan

Ferroportin

Transferrin

Đại thực bào

Sắt dự trữ

Erythroferrone

Fe

Sắt không chỉ cần thiết cho tạo hemoglobin

#align(center)[
  #rect(width: 80%, height: 120pt, stroke: 0.5pt + rgb("aaaaaa"), fill: rgb("f9f9f9"))[
    #align(center + horizon)[#text(size: 8.5pt, fill: rgb("666666"))[[Ảnh nguồn gốc: p4_tbl_0]]]
  ]
  #v(4pt)
  #text(size: 8.5pt, style: "italic", fill: rgb("333333"))[表1　鉄分の多い食品の鉄含有量]
]
#v(8pt)
#table(
  columns: (auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[年]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[齢]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[
]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[（]]],
  ),
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(center)[#text(size: 8.5pt)[男]]],
  [#align(center)[#text(size: 8.5pt)[女]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(left)[#text(size: 8.5pt)[0～（月）]]],
  [#align(right)[#text(size: 8.5pt)[6]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(left)[#text(size: 8.5pt)[6～（月）]]],
  [#align(right)[#text(size: 8.5pt)[6]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[15]]],
  [#align(center)[#text(size: 8.5pt)[1～2]]],
  [#align(right)[#text(size: 8.5pt)[7]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[20]]],
  [#align(center)[#text(size: 8.5pt)[3～5]]],
  [#align(right)[#text(size: 8.5pt)[8]]],
  [#align(center)[#text(size: 8.5pt)[None]]],
  [#align(right)[#text(size: 8.5pt)[25]]],
  [#align(center)[#text(size: 8.5pt)[6～8]]],
  [#align(right)[#text(size: 8.5pt)[9]]],
  [#align(right)[#text(size: 8.5pt)[9]]],
  [#align(right)[#text(size: 8.5pt)[30]]],
  [#align(center)[#text(size: 8.5pt)[9～11]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(center)[#text(size: 8.5pt)[10※1]]],
  [#align(right)[#text(size: 8.5pt)[35]]],
  [#align(left)[#text(size: 8.5pt)[12～14]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[35]]],
  [#align(left)[#text(size: 8.5pt)[15～17]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[18～29]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(right)[#text(size: 8.5pt)[12]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[30～49]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(center)[#text(size: 8.5pt)[12※2]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[50～69]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(center)[#text(size: 8.5pt)[12※2]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(center)[#text(size: 8.5pt)[70以上]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(right)[#text(size: 8.5pt)[10]]],
  [#align(right)[#text(size: 8.5pt)[40]]],
  [#align(left)[#text(size: 8.5pt)[妊婦
授乳婦]]],
  [#align(center)[#text(size: 8.5pt)[]]],
  [#align(left)[#text(size: 8.5pt)[＋8
＋8※3]]],
  [#align(left)[#text(size: 8.5pt)[40
40]]],
)
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p4_draw_1.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p4_draw_2.png", width: 155pt, fit: "contain")
]
#v(8pt)
mà còn đóng vai trò quan trọng trong nhiều quá trình chuyển hóa.

Ngoài bổ sung sắt bằng thuốc,

chế độ ăn giàu sắt cũng rất quan trọng.

Sắt heme (từ thực phẩm động vật) được hấp thu tốt hơn

sắt non-heme (từ thực phẩm thực vật).

Gan, thịt đỏ, cá là nguồn sắt heme tốt.

Vitamin C tăng cường hấp thu sắt non-heme.

Trà, cà phê ức chế hấp thu sắt.

Phytate trong ngũ cốc cũng ức chế hấp thu sắt.

Bảng 2 trình bày hàm lượng sắt trong thực phẩm.

Phòng ngừa thiếu sắt bằng chế độ ăn

đặc biệt quan trọng ở phụ nữ trong độ tuổi sinh sản,

phụ nữ mang thai và trẻ em đang phát triển.

Kết hợp nhiều loại thực phẩm đa dạng

là cách hiệu quả nhất để đảm bảo cung cấp đủ sắt.

WHO ước tính rằng khoảng 2 tỷ người trên thế giới

bị thiếu máu, trong đó thiếu máu do thiếu sắt

chiếm phần lớn, đặc biệt ở các nước đang phát triển.

Việc hiểu rõ cơ chế chuyển hóa sắt

và phát triển các phương pháp chẩn đoán, điều trị mới

là rất cần thiết.

Đặc biệt, các thuốc nhắm hepcidin

đang trong giai đoạn phát triển

và có tiềm năng lớn cho điều trị trong tương lai.

8. Thiếu máu sidero-lactic

Thiếu máu sidero-lastic là nhóm bệnh

đặc trưng bởi rối loạn tổng hợp heme

với sự tích lũy sắt trong ty thể hồng cầu non.

Hình thái đặc trưng: hồng cầu non vòng sắt (ringed sideroblast).

Có thể di truyền hoặc mắc phải.

Thể mắc phải thường gặp trong hội chứng rối loạn sinh tủy (MDS).

Sắt huyết thanh tăng, ferritin tăng,

độ bão hòa transferrin tăng.

※111歳女子は12 mg/日 ※2閉経後10 mg/日 ※3分娩後6カ月間 （ 健康・栄養情報研究会：日本人の栄養所要量．

第6次改訂）

豚肉（レバー）7.8 mg/60 g いわし（丸干）1.8 mg/2匹 乾燥ひじき 5.5 mg/大匙1杯

牛（レバー） 2.4 mg/60 g ほっき貝 2.2 mg/50 g 切干大根 1.9 mg/20 g

あさり水煮 11.3 mg/30 g 小松菜 2.8 mg/100 g 焼き海苔 0.8 mg/1枚

カツオ 1.5 mg/80 g ホウレンソウ 6.0 mg/束 高野豆腐 0.4 mg/6 g

ホンマグロ 0.9 mg/80 g ゆで大豆 2 mg/100 g ゴマ 1.8 mg/大匙1杯

牛ひれ肉 2 mg/80 g 春菊 1.7 mg/100 g

鶏もも 0.3 m/80 g パセリ 0.8 mg/10 g

たまご 0.9 mg/個 ブロッコリー 0.7 mg/70 g

（日本鉄バイオサイエンス学会：鉄剤の適正使用による貧血治療指針，2009）

#table(
  columns: (auto, auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[平均鉄摂取量]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[潜在的鉄欠乏]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[鉄欠乏性貧血]]],
  ),
  [#align(left)[#text(size: 8.5pt)[小児，青少年]]],
  [#align(left)[#text(size: 8.5pt)[6.9-8.5 mg]]],
  [#align(right)[#text(size: 8.5pt)[68.6%]]],
  [#align(right)[#text(size: 8.5pt)[1.5%]]],
  [#align(center)[#text(size: 8.5pt)[成人男性]]],
  [#align(left)[#text(size: 8.5pt)[7.9-9.8 mg]]],
  [#align(right)[#text(size: 8.5pt)[4.2%]]],
  [#align(right)[#text(size: 8.5pt)[0%]]],
  [#align(left)[#text(size: 8.5pt)[月経のある成人女性]]],
  [#align(left)[#text(size: 8.5pt)[7.0-7.8 mg]]],
  [#align(right)[#text(size: 8.5pt)[36.2%]]],
  [#align(right)[#text(size: 8.5pt)[11.9%]]],
  [#align(left)[#text(size: 8.5pt)[閉経後の成人女性]]],
  [#align(left)[#text(size: 8.5pt)[8.1-9.0 mg]]],
  [#align(right)[#text(size: 8.5pt)[8.5%]]],
  [#align(right)[#text(size: 8.5pt)[2.8%]]],
)
#v(8pt)
#table(
  columns: (auto, auto, auto),
  stroke: 0.5pt + rgb("cccccc"),
  fill: (col, row) => if row == 0 { rgb("f0f4f8") } else if calc.even(row) { rgb("fafafa") } else { none },
  table.header(repeat: true,
    [#align(center)[#text(weight: "bold", size: 8.5pt)[]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[ヘモグロビン
g/dl]]],
    [#align(center)[#text(weight: "bold", size: 8.5pt)[血清フェリチン
ng/ml]]],
  ),
  [#align(left)[#text(size: 8.5pt)[鉄欠乏性貧血]]],
  [#align(center)[#text(size: 8.5pt)[＜12]]],
  [#align(center)[#text(size: 8.5pt)[＜12]]],
  [#align(left)[#text(size: 8.5pt)[貧血のない鉄欠乏]]],
  [#align(center)[#text(size: 8.5pt)[≧12]]],
  [#align(center)[#text(size: 8.5pt)[＜12]]],
  [#align(center)[#text(size: 8.5pt)[正常]]],
  [#align(center)[#text(size: 8.5pt)[≧12]]],
  [#align(center)[#text(size: 8.5pt)[≧12]]],
)
#v(8pt)
9. Thiếu máu trong bệnh thận mạn

Thiếu máu là biến chứng phổ biến của bệnh thận mạn (CKD),

chủ yếu do giảm sản xuất erythropoietin (EPO).

Thiếu sắt tuyệt đối và chức năng cũng góp phần.

Điều trị: EPO tái tổ hợp (ESA)

kết hợp bổ sung sắt truyền tĩnh mạch.

Mục tiêu hemoglobin: 10～12 g/dL

theo hướng dẫn KDIGO.

Gần đây, chất ức chế HIF-PHD

(Prolyl Hydroxylase Domain inhibitor)

đã được phát triển như phương pháp điều trị mới.

HIF-PHD inhibitor kích hoạt con đường HIF,

tăng sản xuất EPO nội sinh

và tăng hấp thu, sử dụng sắt.

Roxadustat là thuốc đầu tiên trong nhóm này

được phê duyệt tại Nhật Bản.

10. Kết luận

Chuyển hóa sắt là một hệ thống phức tạp

được điều hòa bởi nhiều cơ chế,

trong đó trục hepcidin-ferroportin đóng vai trò trung tâm.

Thiếu máu do thiếu sắt là bệnh phổ biến nhất

nhưng thường bị bỏ sót hoặc điều trị không đầy đủ.

Hiểu biết về cơ chế phân tử của chuyển hóa sắt

mở ra hướng phát triển các phương pháp

chẩn đoán và điều trị mới.

Đặc biệt, vai trò của H. pylori

trong thiếu máu do thiếu sắt không rõ nguyên nhân

và ứng dụng lâm sàng của hepcidin

là những lĩnh vực nghiên cứu đang phát triển.

Tài liệu tham khảo

1) Andrews NC: Forging a field: the golden age of iron biology. Blood 112: 219-230, 2008.

2) Nemeth E, et al: Hepcidin regulates cellular iron efflux by binding to ferroportin and inducing its internalization. Science 306: 2090-2093, 2004.

3) Ganz T: Systemic iron homeostasis. Physiol Rev 93: 1721-1741, 2013.

4) Kautz L, et al: Identification of erythroferrone as an erythroid regulator of iron metabolism. Nat Genet 46: 678-684, 2014.

5) Qu XH, et al: Does Helicobacter pylori infection play a role in iron deficiency anemia? A meta-analysis. World J Gastroenterol 16: 886-896, 2010.

Đặc tập　Thiếu máu: Từ kiến thức cơ bản đến tiền tuyến điều trị

1387 Tạp chí Hội Nội khoa Nhật Bản Tập 104 Số 7

ピロリ菌の関与はより高い可能性がある．この

他，ピロリ菌と鉄剤不応性の鉄欠乏性貧血との

関連を指摘している研究は多く，Yuanらはメタ

アナリシスで，ピロリ菌に感染している症例で

は，鉄剤単剤よりも除菌＋鉄剤治療の方が有意

に貧血の改善が良好であることを報告してい

る5）．最近，本邦からもピロリ菌感染が原因で

と考えられる重症の鉄欠乏性貧血2 例が報告さ

れている6）．症例はいずれも男性でヘモグロビ

ンが4 g/dl台の重症鉄欠乏性貧血で，スクリー

ニングで出血源が同定されず，経口鉄剤のみで

（日本鉄バイオサイエンス学会：鉄剤の適正使用による貧

血治療指針，2009）

2003年国民栄養調査及び日本人の栄養所要量（健康・栄養情報研究会，第6 次改訂）

#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p6_draw_0.png", width: 80%, fit: "contain")
]
#v(8pt)
#align(center)[
  #image("/Users/tranhaibang/.gemini/antigravity-ide/scratch/ai-workforce/production-closure-validation/blind-test-real/process2/assets/asset_p6_draw_1.png", width: 155pt, fit: "contain")
]
#v(8pt)
6) Hershko C, et al: Role of autoimmune gastritis, Helicobacter pylori and celiac disease in refractory or unexplained iron deficiency anemia. Haematologica 90: 585-595, 2005.

7) WHO: Iron deficiency anaemia: assessment, prevention, and control. WHO/NHD/01.3, 2001.

8) Camaschella C: Iron-deficiency anemia. N Engl J Med 372: 1832-1843, 2015.

9) Lopez A, et al: Iron deficiency anaemia. Lancet 387: 907-916, 2016.

10) Harigae H: Iron metabolism and related diseases. Clin Hematol 56: 2248-2256, 2015.

Tóm tắt: Bài tổng quan này trình bày kiến thức cơ bản về chuyển hóa sắt

trong cơ thể và các bệnh thiếu máu liên quan đến sắt.

Trọng tâm là vai trò của trục hepcidin-ferroportin

trong điều hòa sắt và mối liên quan

giữa nhiễm H. pylori và thiếu máu do thiếu sắt.

Đặc tập　Thiếu máu: Từ kiến thức cơ bản đến tiền tuyến điều trị

1388 Tạp chí Hội Nội khoa Nhật Bản Tập 104 Số 7

の元素であるが，ヘプシジンやフェロポーチン

といった，その吸収，利用の調節に関わる分子

が明らかとなったのは最近のことである．これ

らの分子が明らかとなったことで，慢性炎症の

メカニズムが明らかとなり，新たな分子標的薬

の開発につながっている．臨床的にもっとも頻

度が高い貧血は鉄欠乏性貧血であるが，スク

リーニングにより明らかな原因が同定されない

症例も少なくない．これらの症例の発症要因の

1 つとしてピロリ感染による鉄吸収不全が関与

している可能性がいくつかの研究から示唆され

ている．すでに確立されていると思われがちな

鉄代謝のメカニズムや身近で治療が容易と思わ

れがちな鉄欠乏性貧血であるが，未解明な点が

少なからず残されている．今後も古くて新しい

鉄と貧血に関わる新たな知見が得られることを

期待したい．

著者のCOI（conflicts of interest）開示：張替秀郎；講演 料（中外製薬），寄附金（エーザイ，協和発酵キリン）， 寄附講座（中外製薬）

文献

1）	 Andrews NC : Disorders of iron metabolism. N Engl J Med 341 : 1986―1995, 1999. 2）	 Nemeth E, et al : Hepcidin regulates cellular iron efflux by binding to ferroportin and inducing its internalization.  Science 306 : 2090―2093, 2004. 3）	 日本鉄バイオサイエンス学会治療指針作成委員会編：鉄剤の適正使用による貧血治療指針．2009. 4）	 Hershko C, et al : Role of autoimmune gastritis, Hericobacter pylori and celiac disease in refractory or unexpected  iron deficiency anemia. Haematologica 90 : 585―595, 2005. 5）	 Yuan W, et al. Iron deficiency anemia in Hericobacter pylori : meta-analysis of randomized controlled trials. Scand  J Gastroenterol 45 : 665―676, 2010. 6）	 Yamanouchi J, et al : Dramatic and prompt efficacy of Hericobacter pylori eradication in the treatment of severe  refractory iron deficiency anemia in adults. Ann Hematol 93 : 1779―1780, 2014.
